import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * 🗃️ Data export module
 * Id: 08bac3ae-4168-4ece-97ab-46228bad5b45
 * Codename: _data_export_module
 */
export type __DataExportModule = IContentItem<{
    /**
     * Export data (custom)
     * Required: false
     * Id: 1fcb7b70-f684-4587-ace4-9c2863e39c00
     * Codename: export_data
     */
    exportData: Elements.CustomElement;
}>;
