import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type HeroUnit } from './heroUnit';
import { type WSL_Page } from './WSL_Page';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 📧 Email Newsletter
 * Id: 857f714a-57c2-4f6e-a928-8021ec3cec61
 * Codename: _email_newsletter
 */
export type _EmailNewsletter = IContentItem<{
  /**
   * Body (rich_text)
   * Required: false
   * Id: a1e6052c-0572-4ce5-85ef-bad5866593a9
   * Codename: body
   */
  body: Elements.RichTextElement;

  /**
   * Header (modular_content)
   * Required: false
   * Id: e6b31a53-45e2-4c94-89c6-0595e3f1fc61
   * Codename: header
   */
  header: Elements.LinkedItemsElement<HeroUnit>;

  /**
   * Logo (asset)
   * Required: false
   * Id: 5012e2cc-9715-4b67-9a69-114ee5907b08
   * Codename: logo
   */
  logo: Elements.AssetsElement;

  /**
   * Menu (modular_content)
   * Required: false
   * Id: 37eecc74-295b-401b-bd37-bf61a1b7d47d
   * Codename: menu
   */
  menu: Elements.LinkedItemsElement<WSL_Page>;
}>;
