import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 📂 Folder
 * Id: 031af68f-4388-45f8-8401-6fa7f5964a47
 * Codename: _folder
 */
export type _Folder = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 55a6d417-86e9-4525-9088-27c8847c2046
   * Codename: content
   */
  content: Elements.LinkedItemsElement<IContentItem>;
}>;
