import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 📝 Trial
 * Id: dfd8f840-843e-4231-8027-e089829812ae
 * Codename: trial
 */
export type _Trial = IContentItem<{
  /**
   * Company name (text)
   * Required: false
   * Id: 5364e864-36f6-48c3-8961-1b5e13513fc4
   * Codename: company_name
   */
  companyName: Elements.TextElement;

  /**
   * Domain URL (text)
   * Required: false
   * Id: 450f4bdd-b696-49e6-af50-2786ee180f30
   * Codename: domain_url
   */
  domainUrl: Elements.TextElement;

  /**
   * Email address (text)
   * Required: false
   * Id: 24a9182d-af54-42a6-9048-230a255d44a0
   * Codename: email_address
   */
  emailAddress: Elements.TextElement;

  /**
   * Environment ID (text)
   * Required: false
   * Id: cbbfda22-1c8c-4afb-9de1-06c17bc4d57a
   * Codename: environment_id
   */
  environmentId: Elements.TextElement;

  /**
   * Log (text)
   * Required: false
   * Id: 7bbbf8d5-049e-4c0f-824a-def26347b368
   * Codename: log
   */
  log: Elements.TextElement;

  /**
   * When started (date_time)
   * Required: false
   * Id: 5041a617-d683-4d02-8dd7-9ec62b896e30
   * Codename: when_started
   */
  whenStarted: Elements.DateTimeElement;
}>;
