import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Android Preview
 * Id: 4e5e8820-a250-4e70-877c-c57111b6e066
 * Codename: android_preview
 */
export type AndroidPreview = IContentItem<{}>;
