import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Android Published
 * Id: 3e206d93-c3ff-4f56-bbce-823dddb213f4
 * Codename: android_published
 */
export type AndroidPublished = IContentItem<{}>;
