import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Authentication Panel
 * Id: 4a109b83-997b-44d5-b47e-0703ac2357a0
 * Codename: authentication_panel
 */
export type AuthenticationPanel = IContentItem<{}>;
