import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Authentication Panel
 * Id: c934a018-cffa-4a21-9c42-3662863618b7
 * Codename: authentication_panel
 */
export type AuthenticationPanel = IContentItem<{}>;
