import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Block_CallToAction } from './Block_CallToAction';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Image Container
 * Id: 6ebb749b-5eaf-44f6-8a5e-268921144349
 * Codename: image_container
 */
export type Block_ImageContainer = IContentItem<{
  /**
   * Call to Action (modular_content)
   * Required: false
   * Id: b1f671bb-9594-4355-b4b4-6d94013043da
   * Codename: call_to_action
   */
  callToAction: Elements.LinkedItemsElement<Block_CallToAction>;

  /**
   * Content (rich_text)
   * Required: false
   * Id: fb8a6471-ce6b-446b-8034-19c921ee5683
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * Heading (text)
   * Required: false
   * Id: 9cd23f04-c571-4ebd-86e0-11f3ad6503d7
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 569f29a5-57c5-49ef-a120-5f4931d34acf
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Image location (multiple_choice)
   * Required: false
   * Id: a537365b-e81b-4f70-b34b-de4f63e26815
   * Codename: image_location
   */
  imageLocation: Elements.MultipleChoiceElement;
}>;
