import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Tweet Embed
 * Id: ea415074-cd8b-49df-aff1-390afebde27a
 * Codename: tweet_embed
 */
export type Block_TweetEmbed = IContentItem<{
  /**
   * Tweet ID (custom)
   * Required: false
   * Id: b51015a1-ef4c-4824-af43-d5117b477293
   * Codename: tweet_id
   */
  tweetId: Elements.CustomElement;
}>;
