import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Hubspot Form
 * Id: 72ae336f-85d3-48c6-84da-0450a93c8c8b
 * Codename: hubspot_form
 */
export type Block_HubspotForm = IContentItem<{
  /**
   * Form (custom)
   * Required: false
   * Id: db7dcc9b-a179-44f2-ab48-18d679a770be
   * Codename: form
   */
  form: Elements.CustomElement;
}>;
