import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Image Container
 * Id: 6ebb749b-5eaf-44f6-8a5e-268921144349
 * Codename: image_container
 */
export type Block_ImageContainer = IContentItem<{
  /**
   * Content (rich_text)
   * Required: false
   * Id: fb8a6471-ce6b-446b-8034-19c921ee5683
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 569f29a5-57c5-49ef-a120-5f4931d34acf
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Image location (multiple_choice)
   * Required: false
   * Id: a537365b-e81b-4f70-b34b-de4f63e26815
   * Codename: image_location
   */
  imageLocation: Elements.MultipleChoiceElement;

  /**
   * Title (text)
   * Required: false
   * Id: 9fabf313-2452-4f1f-9de0-c6ecffc5b4f9
   * Codename: title
   */
  title: Elements.TextElement;
}>;
