import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Fact } from './fact';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Stack
 * Id: 43b9af7c-6e78-48ad-9275-11176e9eccb1
 * Codename: stack
 */
export type Block_Stack = IContentItem<{
  /**
   * Message (text)
   * Required: false
   * Id: 05ea7659-6896-4adf-936f-400d7444beee
   * Codename: message
   */
  message: Elements.TextElement;

  /**
   * Stack (modular_content)
   * Required: false
   * Id: 1e73d80b-9944-4593-ba8a-c4ffd0ceff85
   * Codename: stack
   */
  stack: Elements.LinkedItemsElement<Fact>;

  /**
   * Title (text)
   * Required: false
   * Id: dad04087-871c-45ad-9131-a7d5a0173554
   * Codename: title
   */
  title: Elements.TextElement;
}>;
