import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧩 Callout
 * Id: 4b6a742f-4c14-4ee6-95be-185e881c507b
 * Codename: callout
 */
export type Component_Callout = IContentItem<{
  /**
   * Content (rich_text)
   * Required: true
   * Id: c9317a01-da27-46b0-8afd-93257976bb76
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * Type (multiple_choice)
   * Required: true
   * Id: cc80a83f-c117-42b0-99f3-7668e3181809
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;
}>;
