import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Content Chunk
 * Id: feaac754-fe8a-499d-af52-a7db0bb65499
 * Codename: content_chunk
 */
export type ContentChunk = IContentItem<{
  /**
   * Background color (custom)
   * Required: false
   * Id: 0b0058cd-dd18-4351-8c9b-dd786900d46d
   * Codename: background_color
   */
  backgroundColor: Elements.CustomElement;

  /**
   * Content (rich_text)
   * Required: false
   * Id: 243ad7ec-37bf-4152-a858-1a2cbdb144be
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * Text alginment (multiple_choice)
   * Required: false
   * Id: 241e6bd2-d1e7-40f5-a5e1-f8157ce38887
   * Codename: text_alginment
   */
  textAlginment: Elements.MultipleChoiceElement;
}>;
