import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Content Chunk
 * Id: feaac754-fe8a-499d-af52-a7db0bb65499
 * Codename: content_chunk
 */
export type ContentChunk = IContentItem<{
    /**
     * Background color (custom)
     * Required: false
     * Id: 4a482be5-17a9-4438-b1b4-9f7f1f3aafc1
     * Codename: background_color
     */
    backgroundColor: Elements.CustomElement;

    /**
     * Content (rich_text)
     * Required: false
     * Id: 243ad7ec-37bf-4152-a858-1a2cbdb144be
     * Codename: content
     */
    content: Elements.RichTextElement;

    /**
     * Text alignment (multiple_choice)
     * Required: false
     * Id: 99643538-9d24-4948-85e0-82bd4a5f31e0
     * Codename: text_alignment
     */
    textAlignment: Elements.MultipleChoiceElement;
}>;
