import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CourseCategory } from '../taxonomies/courseCategory';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Course Listing
 * Id: 18b3b0be-6bd3-47a8-8edb-7d4708089ce2
 * Codename: course_listing
 */
export type CourseListing = IContentItem<{
  /**
   * Course category (taxonomy)
   * Required: false
   * Id: 5ed013d8-df5b-493f-84e5-3a08a9746cbb
   * Codename: course_category
   */
  courseCategory: Elements.TaxonomyElement<CourseCategory>;

  /**
   * Title (text)
   * Required: false
   * Id: 151600b5-f75c-456e-9e56-ac43cea763ad
   * Codename: title
   */
  title: Elements.TextElement;
}>;
