import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type EventType } from '../taxonomies/eventType';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Event Listing
 * Id: 37064205-60e7-4f6e-8154-7a9e12d350e1
 * Codename: event_listing
 */
export type EventListing = IContentItem<{
    /**
     * Event Type (taxonomy)
     * Required: false
     * Id: 389b37f1-39a1-430a-929c-23746beb51e7
     * Codename: event_type
     */
    eventType: Elements.TaxonomyElement<EventType>;

    /**
     * Title (text)
     * Required: false
     * Id: 007ee0ab-da95-46c7-91b6-a1eef896bacd
     * Codename: title
     */
    title: Elements.TextElement;
}>;
