import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Fact
 * Id: a978a45b-5109-4210-b694-593fef32ad51
 * Codename: fact
 */
export type Fact = IContentItem<{
  /**
   * Image (asset)
   * Required: false
   * Id: f9ac4cbc-cb0e-4131-b556-52134d6b5698
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Message (text)
   * Required: false
   * Id: 7086d6b6-458b-4a98-bc10-29003d9935e5
   * Codename: message
   */
  message: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 28e44fe7-8be9-440d-926a-88b9f08f05b7
   * Codename: title
   */
  title: Elements.TextElement;
}>;
