import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * FAQ
 * Id: 44e0a36e-2ff4-4e53-85da-21efc87e58e7
 * Codename: faq
 */
export type FAQ = IContentItem<{
    /**
     * Answer (rich_text)
     * Required: false
     * Id: 7f90c20c-375e-4826-b3aa-de7e38d98b42
     * Codename: answer
     */
    answer: Elements.RichTextElement;

    /**
     * Question (text)
     * Required: false
     * Id: 68930750-475f-4793-8c74-30688769fc50
     * Codename: question
     */
    question: Elements.TextElement;
}>;
