import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Footer
 * Id: 036b48b0-4e5f-4e2c-a11a-824333e6cfce
 * Codename: footer
 */
export type Footer = IContentItem<{
    /**
     * Copyright notice (text)
     * Required: false
     * Id: 7fb7bfa2-e730-4e98-8ecd-9393ea219f26
     * Codename: copyright_notice
     */
    copyrightNotice: Elements.TextElement;
}>;
