import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Form (Hubspot integration)
 * Id: 72ae336f-85d3-48c6-84da-0450a93c8c8b
 * Codename: form
 */
export type FormHubspotIntegration = IContentItem<{
    /**
     * Form (custom)
     * Required: false
     * Id: db7dcc9b-a179-44f2-ab48-18d679a770be
     * Codename: form
     */
    form: Elements.CustomElement;
}>;
