import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Form (GatedContent integration)
 * Id: 540c71c8-0463-42dd-9563-695a0ae0a6b9
 * Codename: form_gatedcontent
 */
export type FormGatedContentIntegration = IContentItem<{
    /**
     * Forms (custom)
     * Required: false
     * Id: 9aa5be82-4b6d-45dd-aead-df393678b143
     * Codename: forms
     */
    forms: Elements.CustomElement;
}>;
