import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ContentChunk } from './ContentChunk';
import { type LayoutOption } from '../content-type-snippets/layoutOption';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Grid Component
 * Id: 6d5870ea-683c-4597-ab21-673deb08ab44
 * Codename: grid_component
 */
export type GridComponent = IContentItem<{
    /**
     * Columns (number)
     * Required: false
     * Id: a75e0d7f-5035-4713-aa89-d5deb7740734
     * Codename: columns
     */
    columns: Elements.NumberElement;

    /**
     * Content (modular_content)
     * Required: false
     * Id: 31ddf2b1-dbf1-49d1-aa09-79404463703b
     * Codename: content
     */
    content: Elements.LinkedItemsElement<ContentChunk>;
}> &
    LayoutOption;
