import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CallToAction } from './callToAction';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Hero Unit
 * Id: 0a455385-90a1-4ccc-88af-ce9abd6c07a4
 * Codename: hero_unit
 */
export type HeroUnit = IContentItem<{
    /**
     * Background image (asset)
     * Required: false
     * Id: 8e3aa740-0f46-4827-bd01-6752557b37dd
     * Codename: background_image
     */
    backgroundImage: Elements.AssetsElement;

    /**
     * Call to Action (modular_content)
     * Required: false
     * Id: dfd3a2da-b0a2-49af-8c25-f96fb47bbff7
     * Codename: call_to_action
     */
    callToAction: Elements.LinkedItemsElement<CallToAction>;

    /**
     * Content (rich_text)
     * Required: false
     * Id: 99ebe8aa-7069-431f-b258-05900a9c11d6
     * Codename: content
     */
    content: Elements.RichTextElement;

    /**
     * Title (text)
     * Required: false
     * Id: dbf21840-7f55-4f14-a926-05ee07a98118
     * Codename: title
     */
    title: Elements.TextElement;
}>;
