import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Instagram Embed
 * Id: 5e4c7a3e-ff1d-45ca-bea4-46fd872860c3
 * Codename: instagram_embed
 */
export type InstagramEmbed = IContentItem<{
  /**
   * Instagram URL (custom)
   * Required: false
   * Id: 34f37452-501a-47f2-8eb6-1c83d3174f21
   * Codename: instagram_url
   */
  instagramUrl: Elements.CustomElement;
}>;
