import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Key feature
 * Id: 8790b66e-80dd-4ad8-966a-53c7f2c59a58
 * Codename: key_feature
 */
export type KeyFeature = IContentItem<{
  /**
   * Text (text)
   * Required: false
   * Id: 2c8bb172-49e1-4590-b8e0-533df2f9cc8b
   * Codename: text
   */
  text: Elements.TextElement;
}>;
