import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Milestone
 * Id: 1df5b589-13e7-4331-bbdd-761bd6255cdc
 * Codename: milestone
 */
export type Milestone = IContentItem<{
    /**
     * Icon (optional) (asset)
     * Required: false
     * Id: 4b497516-12f3-4bd2-a3fb-bc4120fb808e
     * Codename: icon__optional_
     */
    iconOptional: Elements.AssetsElement;

    /**
     * Subtitle (text)
     * Required: true
     * Id: 9e57f001-a7da-467a-a194-a58ddfc28628
     * Codename: subtitle
     */
    subtitle: Elements.TextElement;

    /**
     * Title (text)
     * Required: true
     * Id: 1c5cdfbb-69c4-4b9b-83c8-8992d5407c2d
     * Codename: title
     */
    title: Elements.TextElement;
}>;
