import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Milestone } from './milestone';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Milestone Listing
 * Id: 477fe0bd-c927-4e31-a3f2-f14c17dc2c38
 * Codename: milestone_listing
 */
export type MilestoneListing = IContentItem<{
    /**
     * Milestones (modular_content)
     * Required: false
     * Id: 8351781d-29fc-40e3-8224-ce65c22f29f6
     * Codename: grid_items
     */
    gridItems: Elements.LinkedItemsElement<Milestone>;
}>;
