import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Panel
 * Id: cd495da0-4247-4456-8d83-288a777f6c23
 * Codename: _panel
 */
export type Panel = IContentItem<{
  /**
   * Content (rich_text)
   * Required: false
   * Id: 09430f5c-f91b-4d7f-b2e3-df203dbc4c94
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 0c947609-33fc-49d4-8d89-fea08403a503
   * Codename: image
   */
  image: Elements.AssetsElement;
}>;
