import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Person
 * Id: 8f37c482-5457-417b-8c61-7e28a8035cf0
 * Codename: person
 */
export type Person = IContentItem<{
    /**
     * Bio (rich_text)
     * Required: false
     * Id: 962a1f4a-57f2-4cd2-bf5c-8d25aca7f932
     * Codename: bio
     */
    bio: Elements.RichTextElement;

    /**
     * First name (text)
     * Required: false
     * Id: 0e288622-5bd2-406b-a770-a950a115f314
     * Codename: first_name
     */
    firstName: Elements.TextElement;

    /**
     * Last name (text)
     * Required: false
     * Id: 367814b8-8c12-48af-b248-d92cb132583f
     * Codename: last_name
     */
    lastName: Elements.TextElement;

    /**
     * Occupation (text)
     * Required: false
     * Id: 233c304b-3558-4fc2-b077-d44a7fd3cbb2
     * Codename: occupation
     */
    occupation: Elements.TextElement;

    /**
     * Photograph (asset)
     * Required: false
     * Id: 34213e8b-f1e7-455b-9da6-28a73bf5c688
     * Codename: photograph
     */
    photograph: Elements.AssetsElement;
}>;
