import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type OpenGraphMetadata } from '../content-type-snippets/openGraphMetadata';
import { type ProductCategory } from '../taxonomies/productCategory';
import { type SEOMetadata } from '../content-type-snippets/SEOMetadata';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Product
 * Id: 62fcbb78-ab65-4247-99cc-e29bb789133d
 * Codename: product
 */
export type Product = IContentItem<{
  /**
   * Body (rich_text)
   * Required: false
   * Id: 10e3b6eb-79f4-48d9-8b73-e8d7b6ccf9f0
   * Codename: body
   */
  body: Elements.RichTextElement;

  /**
   * CommerceTools integration (custom)
   * Required: false
   * Id: 6ccb3e3b-5625-4bec-9b01-9c72d9c0f797
   * Codename: commercetools_integration
   */
  commercetoolsIntegration: Elements.CustomElement;

  /**
   * Connectivity (text)
   * Required: false
   * Id: 7f5d1831-69d9-4321-86dd-8ba6bd6970b2
   * Codename: connectivity
   */
  connectivity: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 59322205-f074-402c-9871-334cdcf5c4e1
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Dimensions (WxDxH) (text)
   * Required: false
   * Id: 0fac8073-3fd0-43e1-aa74-a03dc236f1e8
   * Codename: dimensions__wxdxh_
   */
  dimensionsWxdxh: Elements.TextElement;

  /**
   * Energy Efficiency Rating (text)
   * Required: false
   * Id: d3999aa7-f2ae-4339-af34-9fde4ef02182
   * Codename: energy_efficiency_rating
   */
  energyEfficiencyRating: Elements.TextElement;

  /**
   * Key features (rich_text)
   * Required: false
   * Id: 925a54fa-b9b0-4201-9dbb-376d76a64e7b
   * Codename: key_features
   */
  keyFeatures: Elements.RichTextElement;

  /**
   * Model (text)
   * Required: false
   * Id: 822ab7f4-abe0-44e5-b48d-e463d9a5bc97
   * Codename: model
   */
  model: Elements.TextElement;

  /**
   * Noise Level (in dB) (text)
   * Required: false
   * Id: 02d8bc0e-e0e9-4d64-9690-e597990f98df
   * Codename: noise_level
   */
  noiseLevel: Elements.TextElement;

  /**
   * Price (number)
   * Required: false
   * Id: 8147b730-1174-440f-b66c-3c7052a27c13
   * Codename: price
   */
  price: Elements.NumberElement;

  /**
   * Product category (taxonomy)
   * Required: false
   * Id: 9cb23fa0-7975-40f3-9b2e-284566ed5610
   * Codename: product_category
   */
  productCategory: Elements.TaxonomyElement<ProductCategory>;

  /**
   * Product image (asset)
   * Required: false
   * Id: ef97bfab-e78d-462a-9a10-092f5dbc133e
   * Codename: product_image
   */
  productImage: Elements.AssetsElement;

  /**
   * Shopify integration (custom)
   * Required: false
   * Id: 308ccf0a-d414-4d17-8f29-90e09fcfbff7
   * Codename: shopify_integration
   */
  shopifyIntegration: Elements.CustomElement;

  /**
   * SKU (text)
   * Required: false
   * Id: 89b5849d-c60a-4a06-9c02-d4dcd74ef692
   * Codename: sku
   */
  sku: Elements.TextElement;

  /**
   * Specifications (rich_text)
   * Required: false
   * Id: 47705b37-0590-479e-84d3-62c1e58581ce
   * Codename: specifications
   */
  specifications: Elements.RichTextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 11b1fdeb-c495-4b26-9004-7eb7d1cc1fef
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Total Capacity (text)
   * Required: false
   * Id: 93623a2e-ab6a-4369-9e94-b89b208d4edc
   * Codename: total_capacity
   */
  totalCapacity: Elements.TextElement;

  /**
   * Slug (url_slug)
   * Required: false
   * Id: 93ac7a11-2b9f-410c-9ce7-9d95e90b0960
   * Codename: url
   */
  url: Elements.UrlSlugElement;
}> &
  OpenGraphMetadata &
  SEOMetadata;
