import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ProductCategory } from '../taxonomies/productCategory';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Product Listing
 * Id: 18b3b0be-6bd3-47a8-8edb-7d4708089ce2
 * Codename: product_listing
 */
export type ProductListing = IContentItem<{
    /**
     * Product category (taxonomy)
     * Required: false
     * Id: 675d419a-5bab-4483-88c1-8fb9c09f991a
     * Codename: product_category
     */
    productCategory: Elements.TaxonomyElement<ProductCategory>;

    /**
     * Title (text)
     * Required: false
     * Id: 151600b5-f75c-456e-9e56-ac43cea763ad
     * Codename: title
     */
    title: Elements.TextElement;
}>;
