import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ProductCategory } from '../taxonomies/productCategory';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Product Listing
 * Id: a38cad30-edde-49a3-b11e-be1e8c79b622
 * Codename: product_listing
 */
export type ProductListing = IContentItem<{
  /**
   * Product category (taxonomy)
   * Required: false
   * Id: 3b0a6f8c-45b5-43d9-86ed-318b70e3918c
   * Codename: product_category
   */
  productCategory: Elements.TaxonomyElement<ProductCategory>;

  /**
   * Title (text)
   * Required: false
   * Id: 1b511d67-e929-4a92-b579-06cb57aa79be
   * Codename: title
   */
  title: Elements.TextElement;
}>;
