import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Robots.txt
 * Id: 73c0aa87-131e-459c-bdcd-0d4942d16c85
 * Codename: robots_txt
 */
export type RobotsTxt = IContentItem<{
    /**
     * Content (text)
     * Required: false
     * Id: ba26d3a5-9f88-422e-bcb5-4b9bc85a85e2
     * Codename: content
     */
    content: Elements.TextElement;
}>;
