import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Site Configuration
 * Id: 971ded8c-469f-476d-b7c4-716842db4027
 * Codename: site_configuration
 */
export type SiteConfiguration = IContentItem<{
  /**
   * Search Corporate (custom)
   * Required: false
   * Id: deff17fe-9434-481d-ad00-6aef09a62b9b
   * Codename: search_corporate
   */
  searchCorporate: Elements.CustomElement;

  /**
   * Search Knowledgebase (custom)
   * Required: false
   * Id: 63538a69-cdc4-4eb4-8632-5307189d8c03
   * Codename: search_knowledgebase
   */
  searchKnowledgebase: Elements.CustomElement;

  /**
   * Translation (custom)
   * Required: false
   * Id: 1fd5cae8-cd8a-46fd-80f4-18c92897d543
   * Codename: translation
   */
  translation: Elements.CustomElement;
}>;
