import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Site Configuration
 * Id: 971ded8c-469f-476d-b7c4-716842db4027
 * Codename: site_configuration
 */
export type SiteConfiguration = IContentItem<{
  /**
   * Create new trial (custom)
   * Required: false
   * Id: 98740228-7d68-47a2-8b2a-854696fbac6c
   * Codename: create_new_trial
   */
  createNewTrial: Elements.CustomElement;

  /**
   * Translation (custom)
   * Required: false
   * Id: 1fd5cae8-cd8a-46fd-80f4-18c92897d543
   * Codename: translation
   */
  translation: Elements.CustomElement;
}>;
