import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Specification
 * Id: e3481ec4-60df-4233-a5e9-15ceed316bb4
 * Codename: specification
 */
export type Specification = IContentItem<{
  /**
   * Details (text)
   * Required: false
   * Id: ea37105f-0e3e-4d89-a636-1330368f25c1
   * Codename: details
   */
  details: Elements.TextElement;

  /**
   * Name (text)
   * Required: false
   * Id: 4dd9e63f-ba42-48e8-919e-ab9b49d5b0ac
   * Codename: name
   */
  name: Elements.TextElement;
}>;
