import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Person } from './person';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Testimonial
 * Id: d30689be-9900-4d54-a549-e919346f7990
 * Codename: testimonial
 */
export type Testimonial = IContentItem<{
    /**
     * Author (modular_content)
     * Required: false
     * Id: f60caa40-5a31-47e8-9e3c-be862631381c
     * Codename: author
     */
    author: Elements.LinkedItemsElement<Person>;

    /**
     * Quote (text)
     * Required: false
     * Id: b0a76be2-49f9-44d0-a565-bf61f70f0c93
     * Codename: quote
     */
    quote: Elements.TextElement;
}>;
