import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Page } from './page';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * 💡 Web Spotlight Root
 * Id: 70a78305-2ef2-4f5d-9677-b01866e2f472
 * Codename: web_spotlight_root
 */
export type WSL_WebSpotlightRoot = IContentItem<{
    /**
     * Content (rich_text)
     * Required: false
     * Id: cfacf602-c3a9-44d5-bafd-aea5af865ab9
     * Codename: content
     */
    content: Elements.RichTextElement;

    /**
     * Hide (multiple_choice)
     * Required: false
     * Id: cc38fd0e-0bbd-4b00-a011-5c09fd885b97
     * Codename: hide
     */
    hide: Elements.MultipleChoiceElement;

    /**
     * Logo (asset)
     * Required: false
     * Id: 5d7a0146-b986-4587-bf5c-3ba3111aa441
     * Codename: logo
     */
    logo: Elements.AssetsElement;

    /**
     * Subpages (subpages)
     * Required: false
     * Id: 68783b8a-a680-4d5e-aed1-5e136815f4ef
     * Codename: subpages
     */
    subpages: Elements.LinkedItemsElement<Page>;

    /**
     * Title (text)
     * Required: false
     * Id: f66fd9c8-1894-4223-979a-0b829cb0ece2
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * URL (url_slug)
     * Required: false
     * Id: 48a58dda-a112-443d-853c-d99d3012944d
     * Codename: url
     */
    url: Elements.UrlSlugElement;
}>;
