import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * YouTube Embed
 * Id: 269c7ce3-1d74-41cd-bd35-2d5530aab4b3
 * Codename: youtube_embed
 */
export type YouTubeEmbed = IContentItem<{
    /**
     * Autoplay (multiple_choice)
     * Required: false
     * Id: d59de605-0b0a-4e6f-9758-236a8cda250f
     * Codename: autoplay
     */
    autoplay: Elements.MultipleChoiceElement;

    /**
     * Body (rich_text)
     * Required: false
     * Id: a2b286f6-be90-4ba4-83b7-fd217b1cecfb
     * Codename: body
     */
    body: Elements.RichTextElement;

    /**
     * End time (number)
     * Required: false
     * Id: 7b78f5bf-8fe1-4fb2-ac57-32f9058862c7
     * Codename: end_time
     *
     * Time in seconds, so if you want to end the video at 1:30 you fill in 90
     */
    endTime: Elements.NumberElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 22365200-26af-4dd7-a41b-23f2807dca56
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Start time (number)
     * Required: false
     * Id: 54a9d1b9-98bb-4e62-8b7c-f3a55d82f701
     * Codename: start_time
     *
     * Time in seconds, so if you want to end the video at 1:30 you fill in 90
     */
    startTime: Elements.NumberElement;

    /**
     * Title (text)
     * Required: false
     * Id: e5b3b337-e250-47a6-a5f7-7dfd8cccd6fd
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * YouTube (custom)
     * Required: true
     * Id: 216caf7c-b592-4517-ae81-54fa69fa2d1f
     * Codename: youtube
     */
    youtube: Elements.CustomElement;
}>;
