/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Article Category
 * Id: 056cd0d4-6b76-4d5a-b8d9-b36a87ade13f
 * Codename: article_type
 */
export type ArticleCategory =
    | 'ai'
    | 'client_support_and_satisfaction'
    | 'company'
    | 'customer_success_stories'
    | 'energy'
    | 'engineering_'
    | 'flux_capacitor'
    | 'history'
    | 'industry_revolution'
    | 'industry_trends_and_insights'
    | 'innovation_'
    | 'investors'
    | 'learning_and_adaptation'
    | 'plutonium'
    | 'product_spotlights'
    | 'recyclables'
    | 'renewable_energy'
    | 'research_and_development_'
    | 'robotics_'
    | 'sustainability_'
    | 'sustainability_and_green_manufacturing'
    | 'technology_'
    | 'time_travel'
    | 'waste';
