/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Article Category
 * Id: 056cd0d4-6b76-4d5a-b8d9-b36a87ade13f
 * Codename: article_type
 */
export type ArticleCategory =
  | 'company_news_and_updates'
  | 'industry_trends_and_insights'
  | 'product_spotlights'
  | 'sustainability_and_green_manufacturing';
