/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Channels
 * Id: 06a7a661-2c35-483a-bf0a-a296717ea888
 * Codename: channels
 */
export type Channels = 'desktop' | 'display' | 'facebook' | 'instagram' | 'mobile' | 'social' | 'tablet' | 'x';
