/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Course type
 * Id: 0531e34e-3fdd-423e-9d6c-1d25abfd8a48
 * Codename: course_type
 */
export type CourseType = 'ba__hons_' | 'bsc__hons__' | 'mba';
