/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Course category
 * Id: a924d361-0fdb-4fe1-97e6-6de20e73381a
 * Codename: product_category
 */
export type CourseCategory =
  | 'appliances'
  | 'commercial_equipment'
  | 'crime__policing_and_investigation'
  | 'engineering'
  | 'english'
  | 'health_and_clinical_sciences'
  | 'outdoor_equipment'
  | 'smart_home_solutions';
