/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Course category
 * Id: 4c0bd375-e44e-4b92-bfbd-e9e5029352af
 * Codename: course_category
 */
export type CourseCategory =
    | 'allied_health_professions_and_public_health'
    | 'art_and_design'
    | 'business_and_management'
    | 'computer_science'
    | 'crime__policing_and_investigation'
    | 'engineering'
    | 'health_and_clinical_sciences';
