/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Course type
 * Id: 65dd0569-4551-422f-852a-b72d1d228d27
 * Codename: course_type
 */
export type CourseType = 'ba__hons_' | 'bsc__hons__' | 'mba';
