/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Enrollment Status
 * Id: 2609146f-e9d9-41fc-b3f8-696e150c5d2e
 * Codename: enrollment_status
 */
export type EnrollmentStatus = 'full' | 'part';
