/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Enrollment Status
 * Id: f58f9974-0717-4214-9696-df815d799ac3
 * Codename: enrollment_status
 */
export type EnrollmentStatus = 'full_time' | 'part_time';
