/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Event Type
 * Id: 1d733339-ad82-4e7b-8ce3-969528c7ac5e
 * Codename: event_type
 */
export type EventType = 'family_days' | 'flat_racing' | 'jumps_racing' | 'royal_ascot';
