/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Navigation Structures
 * Id: 151341b3-1e49-4793-8649-d56419382f2f
 * Codename: navigation_structures
 */
export type NavigationStructures = 'footer' | 'header';
