/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Personas
 * Id: 79481e3e-273d-42f8-b4b7-cd2c865fc067
 * Codename: personas
 */
export type Personas =
  | 'the_budget_minded_consumer'
  | 'the_environmentally_conscious_consumer'
  | 'the_family_oriented_parent'
  | 'the_tech_savvy_millennial';
