/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Personas
 * Id: 983dbe34-270c-4233-a061-e2b32e9fc706
 * Codename: personas
 */
export type Personas =
    | 'the_budget_conscious_buyer'
    | 'the_eco_conscious_innovator'
    | 'the_industry_expert'
    | 'the_practical_professional'
    | 'the_trendsetter';
