/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Product category
 * Id: a924d361-0fdb-4fe1-97e6-6de20e73381a
 * Codename: product_category
 */
export type ProductCategory =
    | 'circuitboards_and_electronics'
    | 'electronic_cabling_'
    | 'robotics'
    | 'smart_home_appliances'
    | 'time_travel_components';
