/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Product category
 * Id: 587f8563-7e86-44a7-8020-ebd64a4005b1
 * Codename: product_category_587f856
 */
export type ProductCategory =
  | 'appliances'
  | 'commercial_equipment'
  | 'outdoor_equipment'
  | 'smart_home_solutions';
