/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Products
 * Id: 65ed694b-948a-4b5f-8c38-f1847c30fb39
 * Codename: products
 */
export type Products = 'all' | 'car' | 'home' | 'travel';
