/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Product category
 * Id: a924d361-0fdb-4fe1-97e6-6de20e73381a
 * Codename: product_category
 */
export type ProductCategory =
  | 'appliances'
  | 'commercial_equipment'
  | 'outdoor_equipment'
  | 'smart_home_solutions';
