import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Open Graph Metadata
 * Id: 81a6f4b3-64af-4e49-a080-27da56cb912f
 * Codename: open_graph_metadata
 */
export type OpenGraphMetadata = IContentItem<{
    /**
     * OG:Description (text)
     * Required: false
     * Id: 3886ee4b-3434-4587-9aab-d54793e1075f
     * Codename: open_graph_metadata__description
     */
    openGraphMetadataDescription: Elements.TextElement;

    /**
     * OG:Image (asset)
     * Required: false
     * Id: c4f33233-4a38-46af-ae18-ebf534b615d4
     * Codename: open_graph_metadata__image
     *
     * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
     */
    openGraphMetadataImage: Elements.AssetsElement;

    /**
     * OG:Title (text)
     * Required: false
     * Id: e6a6aef9-44af-4f99-82ea-9ceee6f1d526
     * Codename: open_graph_metadata__title
     */
    openGraphMetadataTitle: Elements.TextElement;

    /**
     * OG:Type (text)
     * Required: false
     * Id: 8042b550-cd5a-4149-8aed-b047a54dbc9c
     * Codename: open_graph_metadata__type
     */
    openGraphMetadataType: Elements.TextElement;
}>;
