/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: ⚒ Karma Manufacturing
 * Environment: Production
 * Project Id: a917b5bf-e2e1-011e-0a73-0b317b1e1c33
 */
export const assetFolders = {
  /**
   * Components
   */
  components: {
    id: '3237fb93-c2cb-4105-8a72-828dc4414c75',
    name: 'Components ',
    externalId: undefined,
    folders: {
      /**
       * Image Container
       */
      imageContainer: {
        id: '9e783fb0-ba7c-492e-a78e-af3b6c65c470',
        name: 'Image Container',
        externalId: undefined,
        folders: {},
      },
    },
  },

  /**
   * Events
   */
  events: {
    id: '57a7cf7b-a9cd-4c4c-925e-50f25a70b6f6',
    name: 'Events',
    externalId: undefined,
    folders: {},
  },

  /**
   * Hero images
   */
  heroImages: {
    id: 'bd3084fd-5bb6-438b-a6fb-214af2ea334e',
    name: 'Hero images',
    externalId: undefined,
    folders: {},
  },

  /**
   * Karma Manufacturing
   */
  karmaManufacturing: {
    id: 'ebd4d5ac-bca1-4782-9856-4bce3b53dbc8',
    name: 'Karma Manufacturing',
    externalId: undefined,
    folders: {
      /**
       * Products
       */
      products: {
        id: '5297337a-0b2c-4241-ac13-6c97ac5258dd',
        name: 'Products',
        externalId: undefined,
        folders: {},
      },
    },
  },

  /**
   * Kontent.ai
   */
  kontentAi: {
    id: '5b47b660-729c-44ae-886e-ac9d372f4f62',
    name: 'Kontent.ai',
    externalId: undefined,
    folders: {},
  },

  /**
   * Logo
   */
  logo: {
    id: 'e3a415f4-24af-4904-9f3d-bedc37953bb8',
    name: 'Logo',
    externalId: undefined,
    folders: {},
  },

  /**
   * manufacturing
   */
  manufacturing: {
    id: '6756184a-4269-440c-96e4-31795c046dc5',
    name: 'manufacturing',
    externalId: undefined,
    folders: {},
  },

  /**
   * People
   */
  people: {
    id: '9abbd104-fa6e-4d48-80a8-47e30ba5ca53',
    name: 'People',
    externalId: undefined,
    folders: {},
  },

  /**
   * Products
   */
  products: {
    id: 'cf933db1-5c1d-4c1b-b02a-37c000967853',
    name: 'Products',
    externalId: undefined,
    folders: {},
  },

  /**
   * Stock images
   */
  stockImages: {
    id: '7e5821ae-3a77-42ba-8422-258394677a9b',
    name: 'Stock images',
    externalId: undefined,
    folders: {},
  },

  /**
   * Videos
   */
  videos: {
    id: 'd474c6ae-5612-4f92-8536-9aacf105d8c4',
    name: 'Videos',
    externalId: undefined,
    folders: {},
  },
} as const;
