/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: 🪙 Compare the Market
 * Environment: Production
 * Project Id: de84585d-59fc-0190-f8dd-12e74a4d633f
 */
export const assetFolders = {
  /**
   * Banners
   */
  banners: {
    id: '1db3ea40-1d61-4bda-9014-e551d7a1aebc',
    name: 'Banners',
    externalId: undefined,
    folders: {},
  },

  /**
   * Compare the Market
   */
  compareTheMarket: {
    id: '94f73ba9-32c4-47a2-884f-b5d82a84773b',
    name: 'Compare the Market',
    externalId: undefined,
    folders: {},
  },

  /**
   * Education
   */
  education: {
    id: 'f8c7c5d2-0cd4-498b-bf18-b476a41cc7f4',
    name: 'Education',
    externalId: undefined,
    folders: {},
  },

  /**
   * Healthcare
   */
  healthcare: {
    id: 'a7b52ee1-a9d9-4b47-81c3-57ed5e0ea165',
    name: 'Healthcare',
    externalId: undefined,
    folders: {},
  },

  /**
   * Icons
   */
  icons: {
    id: 'fdccc9f8-a237-481c-a2da-2fe1065b5de2',
    name: 'Icons',
    externalId: undefined,
    folders: {},
  },

  /**
   * Manufacturing
   */
  manufacturing: {
    id: 'ebd4d5ac-bca1-4782-9856-4bce3b53dbc8',
    name: 'Manufacturing',
    externalId: undefined,
    folders: {
      /**
       * Products
       */
      products: {
        id: '5297337a-0b2c-4241-ac13-6c97ac5258dd',
        name: 'Products',
        externalId: undefined,
        folders: {
          /**
           * Mr. Fusion
           */
          mrFusion: {
            id: '26fcd1bf-f505-4f61-a71e-d6ea7f30b90d',
            name: 'Mr. Fusion',
            externalId: undefined,
            folders: {},
          },

          /**
           * Flux Capacitor
           */
          fluxCapacitor: {
            id: '5d64396c-458d-43b7-8d00-c40208ecd3b7',
            name: 'Flux Capacitor',
            externalId: undefined,
            folders: {},
          },
        },
      },

      /**
       * Banners
       */
      banners: {
        id: '7044af1d-e65a-4017-86f3-67f897a9d542',
        name: 'Banners',
        externalId: undefined,
        folders: {},
      },

      /**
       * Global
       */
      global: {
        id: 'a9d17027-f0cf-4c22-9a3b-ffe11f7f0272',
        name: 'Global',
        externalId: undefined,
        folders: {},
      },

      /**
       * Components
       */
      components: {
        id: '5d11f499-718a-4cc5-9b4e-85e82336d023',
        name: 'Components',
        externalId: undefined,
        folders: {},
      },

      /**
       * Profiles
       */
      profiles: {
        id: '55e367b6-8524-4bc4-8199-0a790bee4f11',
        name: 'Profiles',
        externalId: undefined,
        folders: {},
      },

      /**
       * Hero images
       */
      heroImages: {
        id: 'bd3084fd-5bb6-438b-a6fb-214af2ea334e',
        name: 'Hero images',
        externalId: undefined,
        folders: {},
      },
    },
  },

  /**
   * People
   */
  people: {
    id: 'dc394f3d-23f6-4f70-818d-dedcb2091da2',
    name: 'People',
    externalId: undefined,
    folders: {},
  },

  /**
   * zArchived
   */
  zArchived: {
    id: 'ddf77744-cf98-4867-b2d7-81495805cc6d',
    name: 'zArchived',
    externalId: undefined,
    folders: {
      /**
       * Logos
       */
      logos: {
        id: 'e3a415f4-24af-4904-9f3d-bedc37953bb8',
        name: 'Logos',
        externalId: undefined,
        folders: {},
      },
    },
  },
} as const;
