/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: ⚒ EliteBuild Manufacturing
 * Environment: Production
 * Project Id: 768414e0-b626-0188-3a49-5d5d02e33dda
 */
export const collections = {
  /**
   * Career at EliteBuild (HR Department)
   */
  career_at_elitebuild__hr_department_: {
    codename: 'career_at_elitebuild__hr_department_',
    id: '751ba16d-c572-4c04-9ffc-9790e35ae7ed',
    name: 'Career at EliteBuild (HR Department)',
  },

  /**
   * EliteBuild
   */
  elitebuild: {
    codename: 'elitebuild',
    id: '6463921f-f13e-4119-82bd-54df8a9432b0',
    name: 'EliteBuild',
  },

  /**
   * Elysium
   */
  elysium: {
    codename: 'elysium',
    id: 'e9395dd3-8746-4e0c-9653-caa9850f01a7',
    name: 'Elysium',
  },

  /**
   * Global content
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Global content',
  },

  /**
   * Marketing Campaign
   */
  marketing_campaign: {
    codename: 'marketing_campaign',
    id: '2f3d219c-7afa-4545-9742-25876bdbf8f3',
    name: 'Marketing Campaign',
  },

  /**
   * Sandbox
   */
  corporate_site: {
    codename: 'corporate_site',
    id: '17bad030-5da7-4bd8-ba75-c5ffde8d526e',
    name: 'Sandbox',
  },

  /**
   * Support
   */
  support: {
    codename: 'support',
    id: '0e91d5c5-a8be-4188-9d1a-cedef1f2652e',
    name: 'Support',
  },
} as const;
