/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: 👩‍🎓 AQA
 * Environment: Production
 * Project Id: 3ef39865-e160-017f-7f2f-0c64e59ad6df
 */
export const collections = {
  /**
   * AQA - Corporate Website
   */
  corporate_site: {
    codename: 'corporate_site',
    id: '17bad030-5da7-4bd8-ba75-c5ffde8d526e',
    name: 'AQA - Corporate Website',
  },

  /**
   * Career at AQA (HR Department)
   */
  career_at_elitebuild__hr_department_: {
    codename: 'career_at_elitebuild__hr_department_',
    id: '751ba16d-c572-4c04-9ffc-9790e35ae7ed',
    name: 'Career at AQA (HR Department)',
  },

  /**
   * EliteBuild
   */
  elitebuild: {
    codename: 'elitebuild',
    id: '6463921f-f13e-4119-82bd-54df8a9432b0',
    name: 'EliteBuild',
  },

  /**
   * Global content
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Global content',
  },

  /**
   * Marketing Campaign
   */
  marketing_campaign: {
    codename: 'marketing_campaign',
    id: '2f3d219c-7afa-4545-9742-25876bdbf8f3',
    name: 'Marketing Campaign',
  },

  /**
   * PDF
   */
  werk_nl: {
    codename: 'werk_nl',
    id: '634de470-28e8-4bd4-b202-e9447f98ec27',
    name: 'PDF',
  },

  /**
   * Support
   */
  support: {
    codename: 'support',
    id: '0e91d5c5-a8be-4188-9d1a-cedef1f2652e',
    name: 'Support',
  },
} as const;
