/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: ⚒ EliteBuild Manufacturing - Master
 * Environment: Development
 * Project Id: a917b5bf-e2e1-011e-0a73-0b317b1e1c33
 */
export const collections = {
  /**
   * Career at EliteBuild (HR Department)
   */
  career_at_elitebuild__hr_department_: {
    codename: 'career_at_elitebuild__hr_department_',
    id: '751ba16d-c572-4c04-9ffc-9790e35ae7ed',
    name: 'Career at EliteBuild (HR Department)',
  },

  /**
   * Global content
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Global content',
  },

  /**
   * Marketing Campaign
   */
  marketing_campaign: {
    codename: 'marketing_campaign',
    id: '2f3d219c-7afa-4545-9742-25876bdbf8f3',
    name: 'Marketing Campaign',
  },

  /**
   * Sandbox
   */
  sandbox: {
    codename: 'sandbox',
    id: '3905681f-dce2-4a90-8dab-425d4b73ea9c',
    name: 'Sandbox',
  },
} as const;
