/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const contentTypes = {
    /**
     *    Page
     */
    page: {
        codename: 'page',
        id: '5aab1bd3-9433-40d2-8e0f-cbda835ec5fd',
        externalId: undefined,
        name: '💡 Page',
        elements: {
            /**
             * Canonical URL (text)
             */
            seo_metadata__canonical_url: {
                codename: 'seo_metadata__canonical_url',
                id: '145b30b0-1438-4e27-998f-c37a23c39393',
                externalId: undefined,
                name: 'Canonical URL',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Content (rich_text)
             */
            content: {
                codename: 'content',
                id: '756bc39a-7d70-4faa-9116-eeacd689ff4f',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'rich_text'
            },

            /**
             * Description (text)
             *
             * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
             */
            seo_metadata__description: {
                codename: 'seo_metadata__description',
                id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Keywords (text)
             */
            seo_metadata__keywords: {
                codename: 'seo_metadata__keywords',
                id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
                externalId: undefined,
                name: 'Keywords',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Navigation Structures (taxonomy)
             */
            navigation_structures: {
                codename: 'navigation_structures',
                id: '943b2571-e126-47ae-814e-179b78aad2f7',
                externalId: undefined,
                name: 'Navigation Structures',
                required: false,
                type: 'taxonomy'
            },

            /**
             * OG Description (text)
             */
            open_graph_metadata__description: {
                codename: 'open_graph_metadata__description',
                id: '3886ee4b-3434-4587-9aab-d54793e1075f',
                externalId: undefined,
                name: 'OG:Description',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Image (asset)
             *
             * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
             */
            open_graph_metadata__image: {
                codename: 'open_graph_metadata__image',
                id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
                externalId: undefined,
                name: 'OG:Image',
                required: false,
                type: 'asset',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Title (text)
             */
            open_graph_metadata__title: {
                codename: 'open_graph_metadata__title',
                id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
                externalId: undefined,
                name: 'OG:Title',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Type (text)
             */
            open_graph_metadata__type: {
                codename: 'open_graph_metadata__type',
                id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
                externalId: undefined,
                name: 'OG:Type',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * Robots Follow (multiple_choice)
             */
            seo_metadata__robots_follow: {
                codename: 'seo_metadata__robots_follow',
                id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
                externalId: undefined,
                name: 'Robots Follow',
                required: false,
                type: 'multiple_choice',
                options: {
                    follow: {
                        name: 'Follow',
                        id: 'b1093b4b-2a6e-4698-affc-86fa0d30dc29',
                        codename: 'follow',
                        externalId: undefined
                    },
                    no_follow: {
                        name: 'No Follow',
                        id: 'ea97e348-ba05-4508-98a5-97d6513735b5',
                        codename: 'no_follow',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Robots Index (multiple_choice)
             */
            seo_metadata__robots_index: {
                codename: 'seo_metadata__robots_index',
                id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
                externalId: undefined,
                name: 'Robots Index',
                required: false,
                type: 'multiple_choice',
                options: {
                    index: {
                        name: 'Index',
                        id: 'a526485d-4693-42f7-954c-62c8fc091674',
                        codename: 'index',
                        externalId: undefined
                    },
                    no_index: {
                        name: 'No Index',
                        id: 'f71db495-aa77-4291-b1fc-7f0818faef52',
                        codename: 'no_index',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Subpages (subpages)
             */
            subpages: {
                codename: 'subpages',
                id: '890cb2c8-fc22-4744-8965-0e8bfe284c62',
                externalId: undefined,
                name: 'Subpages',
                required: false,
                type: 'subpages'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '93218af9-0226-422a-b1a0-27ad0058dcf4',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            },

            /**
             * Title (text)
             *
             * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
             */
            seo_metadata__title: {
                codename: 'seo_metadata__title',
                id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * URL (url_slug)
             */
            url: {
                codename: 'url',
                id: 'a1f23c97-017d-4764-bc39-82050166b371',
                externalId: undefined,
                name: 'URL',
                required: false,
                type: 'url_slug'
            }
        }
    },

    /**
     *    Web Spotlight Root
     */
    web_spotlight_root: {
        codename: 'web_spotlight_root',
        id: '70a78305-2ef2-4f5d-9677-b01866e2f472',
        externalId: undefined,
        name: '💡 Web Spotlight Root',
        elements: {
            /**
             * Canonical URL (text)
             */
            seo_metadata__canonical_url: {
                codename: 'seo_metadata__canonical_url',
                id: '145b30b0-1438-4e27-998f-c37a23c39393',
                externalId: undefined,
                name: 'Canonical URL',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Content (rich_text)
             */
            content: {
                codename: 'content',
                id: 'cfacf602-c3a9-44d5-bafd-aea5af865ab9',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'rich_text'
            },

            /**
             * Description (text)
             *
             * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
             */
            seo_metadata__description: {
                codename: 'seo_metadata__description',
                id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Keywords (text)
             */
            seo_metadata__keywords: {
                codename: 'seo_metadata__keywords',
                id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
                externalId: undefined,
                name: 'Keywords',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Logo (asset)
             */
            logo: {
                codename: 'logo',
                id: '5d7a0146-b986-4587-bf5c-3ba3111aa441',
                externalId: undefined,
                name: 'Logo',
                required: false,
                type: 'asset'
            },

            /**
             * Name (text)
             */
            name: {
                codename: 'name',
                id: 'd53ff95e-3ced-4a2f-9963-e640e6937a8b',
                externalId: undefined,
                name: 'Name',
                required: false,
                type: 'text'
            },

            /**
             * OG Description (text)
             */
            open_graph_metadata__description: {
                codename: 'open_graph_metadata__description',
                id: '3886ee4b-3434-4587-9aab-d54793e1075f',
                externalId: undefined,
                name: 'OG:Description',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Image (asset)
             *
             * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
             */
            open_graph_metadata__image: {
                codename: 'open_graph_metadata__image',
                id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
                externalId: undefined,
                name: 'OG:Image',
                required: false,
                type: 'asset',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Title (text)
             */
            open_graph_metadata__title: {
                codename: 'open_graph_metadata__title',
                id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
                externalId: undefined,
                name: 'OG:Title',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Type (text)
             */
            open_graph_metadata__type: {
                codename: 'open_graph_metadata__type',
                id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
                externalId: undefined,
                name: 'OG:Type',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * Robots Follow (multiple_choice)
             */
            seo_metadata__robots_follow: {
                codename: 'seo_metadata__robots_follow',
                id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
                externalId: undefined,
                name: 'Robots Follow',
                required: false,
                type: 'multiple_choice',
                options: {
                    follow: {
                        name: 'Follow',
                        id: 'b1093b4b-2a6e-4698-affc-86fa0d30dc29',
                        codename: 'follow',
                        externalId: undefined
                    },
                    no_follow: {
                        name: 'No Follow',
                        id: 'ea97e348-ba05-4508-98a5-97d6513735b5',
                        codename: 'no_follow',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Robots Index (multiple_choice)
             */
            seo_metadata__robots_index: {
                codename: 'seo_metadata__robots_index',
                id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
                externalId: undefined,
                name: 'Robots Index',
                required: false,
                type: 'multiple_choice',
                options: {
                    index: {
                        name: 'Index',
                        id: 'a526485d-4693-42f7-954c-62c8fc091674',
                        codename: 'index',
                        externalId: undefined
                    },
                    no_index: {
                        name: 'No Index',
                        id: 'f71db495-aa77-4291-b1fc-7f0818faef52',
                        codename: 'no_index',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Subpages (subpages)
             */
            subpages: {
                codename: 'subpages',
                id: '68783b8a-a680-4d5e-aed1-5e136815f4ef',
                externalId: undefined,
                name: 'Subpages',
                required: false,
                type: 'subpages'
            },

            /**
             * Tagline (text)
             */
            tagline: {
                codename: 'tagline',
                id: '86c798ef-25ed-41e0-92c6-3b566161fd9d',
                externalId: undefined,
                name: 'Tagline',
                required: false,
                type: 'text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'f66fd9c8-1894-4223-979a-0b829cb0ece2',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            },

            /**
             * Title (text)
             *
             * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
             */
            seo_metadata__title: {
                codename: 'seo_metadata__title',
                id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            }
        }
    },

    /**
     * Article
     */
    article: {
        codename: 'article',
        id: '5b4209c9-c672-459c-b8a2-43fd15fede54',
        externalId: undefined,
        name: 'Article',
        elements: {
            /**
             * Abstract (text)
             */
            abstract: {
                codename: 'abstract',
                id: 'bf77669f-5020-4cb7-9342-b9de30afdd77',
                externalId: undefined,
                name: 'Abstract',
                required: false,
                type: 'text'
            },

            /**
             * Article Category (taxonomy)
             */
            article_type: {
                codename: 'article_type',
                id: '2cf6d39e-b61c-4df1-a390-b267b1293f56',
                externalId: undefined,
                name: 'Article type',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Author (modular_content)
             */
            author: {
                codename: 'author',
                id: '9611446a-69b1-44d5-b7c1-9cbd7fa5151a',
                externalId: undefined,
                name: 'Author',
                required: false,
                type: 'modular_content'
            },

            /**
             * Canonical URL (text)
             */
            seo_metadata__canonical_url: {
                codename: 'seo_metadata__canonical_url',
                id: '145b30b0-1438-4e27-998f-c37a23c39393',
                externalId: undefined,
                name: 'Canonical URL',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Content (rich_text)
             */
            content: {
                codename: 'content',
                id: '0746ed7f-f75c-427c-85da-70a71cd14958',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'rich_text'
            },

            /**
             * Description (text)
             *
             * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
             */
            seo_metadata__description: {
                codename: 'seo_metadata__description',
                id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Hero Image (asset)
             */
            hero_image: {
                codename: 'hero_image',
                id: '0ba20928-908d-48ca-b326-5f0f2fff663d',
                externalId: undefined,
                name: 'Hero Image',
                required: false,
                type: 'asset'
            },

            /**
             * Keywords (text)
             */
            seo_metadata__keywords: {
                codename: 'seo_metadata__keywords',
                id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
                externalId: undefined,
                name: 'Keywords',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * OG Description (text)
             */
            open_graph_metadata__description: {
                codename: 'open_graph_metadata__description',
                id: '3886ee4b-3434-4587-9aab-d54793e1075f',
                externalId: undefined,
                name: 'OG:Description',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Image (asset)
             *
             * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
             */
            open_graph_metadata__image: {
                codename: 'open_graph_metadata__image',
                id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
                externalId: undefined,
                name: 'OG:Image',
                required: false,
                type: 'asset',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Title (text)
             */
            open_graph_metadata__title: {
                codename: 'open_graph_metadata__title',
                id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
                externalId: undefined,
                name: 'OG:Title',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Type (text)
             */
            open_graph_metadata__type: {
                codename: 'open_graph_metadata__type',
                id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
                externalId: undefined,
                name: 'OG:Type',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * Publishing date (date_time)
             */
            publishing_date: {
                codename: 'publishing_date',
                id: '99460d45-bd27-480b-b2f5-5ae45c554488',
                externalId: undefined,
                name: 'Publishing date',
                required: false,
                type: 'date_time'
            },

            /**
             * Robots Follow (multiple_choice)
             */
            seo_metadata__robots_follow: {
                codename: 'seo_metadata__robots_follow',
                id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
                externalId: undefined,
                name: 'Robots Follow',
                required: false,
                type: 'multiple_choice',
                options: {
                    follow: {
                        name: 'Follow',
                        id: 'b1093b4b-2a6e-4698-affc-86fa0d30dc29',
                        codename: 'follow',
                        externalId: undefined
                    },
                    no_follow: {
                        name: 'No Follow',
                        id: 'ea97e348-ba05-4508-98a5-97d6513735b5',
                        codename: 'no_follow',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Robots Index (multiple_choice)
             */
            seo_metadata__robots_index: {
                codename: 'seo_metadata__robots_index',
                id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
                externalId: undefined,
                name: 'Robots Index',
                required: false,
                type: 'multiple_choice',
                options: {
                    index: {
                        name: 'Index',
                        id: 'a526485d-4693-42f7-954c-62c8fc091674',
                        codename: 'index',
                        externalId: undefined
                    },
                    no_index: {
                        name: 'No Index',
                        id: 'f71db495-aa77-4291-b1fc-7f0818faef52',
                        codename: 'no_index',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'd92a08b1-2bb1-4880-9dcd-40add106e7c4',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            },

            /**
             * Title (text)
             *
             * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
             */
            seo_metadata__title: {
                codename: 'seo_metadata__title',
                id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * URL (url_slug)
             */
            url: {
                codename: 'url',
                id: 'a9a2ddec-60e0-435e-8cf5-94fe50669640',
                externalId: undefined,
                name: 'URL',
                required: false,
                type: 'url_slug'
            }
        }
    },

    /**
     * Article Listing
     */
    article_listing: {
        codename: 'article_listing',
        id: 'a967cfb4-ce15-4a22-b6e7-a9bf632fbd2b',
        externalId: undefined,
        name: 'Article Listing',
        elements: {
            /**
             * Article Category (taxonomy)
             */
            article_type: {
                codename: 'article_type',
                id: '161367e7-e60f-494c-a130-b497e358a876',
                externalId: undefined,
                name: 'Article type',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'a210727c-e09d-44c0-ba89-908870ece3c0',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Call to Action
     */
    call_to_action: {
        codename: 'call_to_action',
        id: '068970e2-e5ba-44be-8bc4-66acb19547f1',
        externalId: undefined,
        name: 'Call to Action',
        elements: {
            /**
             * Item Target (modular_content)
             */
            item_target: {
                codename: 'item_target',
                id: '513c3019-0fbc-4e4c-9ef5-bc37b7f70dee',
                externalId: undefined,
                name: 'Item Target',
                required: false,
                type: 'modular_content'
            },

            /**
             * Manual Target (text)
             */
            manual_target: {
                codename: 'manual_target',
                id: '03b11077-1053-44dd-8047-c1119d0b393a',
                externalId: undefined,
                name: 'Manual Target',
                required: false,
                type: 'text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'f23fb051-8fdb-4067-b02b-5b4313ceaa06',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Carousel
     */
    carousel: {
        codename: 'carousel',
        id: 'd3157a0b-928c-4c69-b3d5-8816e9e8e406',
        externalId: undefined,
        name: 'Carousel',
        elements: {
            /**
             * Elements (modular_content)
             */
            elements: {
                codename: 'elements',
                id: '0c889cf7-b807-4a92-80bc-c0e500d8f1b5',
                externalId: undefined,
                name: 'Elements',
                required: false,
                type: 'modular_content'
            }
        }
    },

    /**
     * Content Chunk
     */
    content_chunk: {
        codename: 'content_chunk',
        id: 'feaac754-fe8a-499d-af52-a7db0bb65499',
        externalId: undefined,
        name: 'Content Chunk',
        elements: {
            /**
             * Background color (custom)
             */
            background_color: {
                codename: 'background_color',
                id: '4a482be5-17a9-4438-b1b4-9f7f1f3aafc1',
                externalId: undefined,
                name: 'Background color',
                required: false,
                type: 'custom'
            },

            /**
             * Content (rich_text)
             */
            content: {
                codename: 'content',
                id: '243ad7ec-37bf-4152-a858-1a2cbdb144be',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'rich_text'
            },

            /**
             * Text alignment (multiple_choice)
             */
            text_alignment: {
                codename: 'text_alignment',
                id: '99643538-9d24-4948-85e0-82bd4a5f31e0',
                externalId: undefined,
                name: 'Text alignment',
                required: false,
                type: 'multiple_choice',
                options: {
                    left: {
                        name: 'Left',
                        id: '9a516772-e683-4647-be7a-43f90f2b4afa',
                        codename: 'left',
                        externalId: undefined
                    },
                    right: {
                        name: 'Right',
                        id: 'ea514b0d-1671-4dc4-afbe-2f49ef054785',
                        codename: 'right',
                        externalId: undefined
                    },
                    center: {
                        name: 'Center',
                        id: 'e55b1470-8842-4e8f-9007-78c9217dbce4',
                        codename: 'center',
                        externalId: undefined
                    }
                }
            }
        }
    },

    /**
     * Course
     */
    course: {
        codename: 'course',
        id: 'f688aa85-762c-46fa-93d4-14251a9f9efb',
        externalId: undefined,
        name: 'Course',
        elements: {
            /**
             * Body (rich_text)
             */
            body: {
                codename: 'body',
                id: '1263c4aa-fe18-4c5f-bb19-95325bb0d285',
                externalId: undefined,
                name: 'Body',
                required: false,
                type: 'rich_text'
            },

            /**
             * Canonical URL (text)
             */
            seo_metadata__canonical_url: {
                codename: 'seo_metadata__canonical_url',
                id: '145b30b0-1438-4e27-998f-c37a23c39393',
                externalId: undefined,
                name: 'Canonical URL',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Course category (taxonomy)
             */
            course_category: {
                codename: 'course_category',
                id: 'ae3baac8-25fe-45c6-82b0-d854b1c3cacf',
                externalId: undefined,
                name: 'Course category',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Course type (taxonomy)
             */
            course_type: {
                codename: 'course_type',
                id: '98970d5c-f679-44a2-a7b4-942cdd09f99b',
                externalId: undefined,
                name: 'Course type',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Description (text)
             */
            description: {
                codename: 'description',
                id: '33eae92a-5ea6-4ab4-ab6c-ceba4748d71e',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'text'
            },

            /**
             * Description (text)
             *
             * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
             */
            seo_metadata__description: {
                codename: 'seo_metadata__description',
                id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Duration in years (text)
             */
            duration_in_years: {
                codename: 'duration_in_years',
                id: 'aefc5e65-4880-46d7-8670-4140e9ba2d1c',
                externalId: undefined,
                name: 'Duration in years',
                required: false,
                type: 'text'
            },

            /**
             * Enrollment Status (taxonomy)
             */
            enrollment_status: {
                codename: 'enrollment_status',
                id: 'c7538aa2-cb91-42a2-b46a-5b7b5b3d851b',
                externalId: undefined,
                name: 'Enrollment Status',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Fee in   (text)
             */
            fee_in__: {
                codename: 'fee_in__',
                id: '481f1a9f-1228-4ebf-aba5-424269b4f069',
                externalId: undefined,
                name: 'Fee in $',
                required: false,
                type: 'text'
            },

            /**
             * Hero image (asset)
             */
            hero_image: {
                codename: 'hero_image',
                id: '8781208f-d75d-4b31-881b-6d0c17e36cbf',
                externalId: undefined,
                name: 'Hero image',
                required: false,
                type: 'asset'
            },

            /**
             * Keywords (text)
             */
            seo_metadata__keywords: {
                codename: 'seo_metadata__keywords',
                id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
                externalId: undefined,
                name: 'Keywords',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Next start date (date_time)
             */
            next_start_date: {
                codename: 'next_start_date',
                id: '12a06da0-fc66-4938-ba6d-7f451fbdd13a',
                externalId: undefined,
                name: 'Next start date',
                required: false,
                type: 'date_time'
            },

            /**
             * OG Description (text)
             */
            open_graph_metadata__description: {
                codename: 'open_graph_metadata__description',
                id: '3886ee4b-3434-4587-9aab-d54793e1075f',
                externalId: undefined,
                name: 'OG:Description',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Image (asset)
             *
             * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
             */
            open_graph_metadata__image: {
                codename: 'open_graph_metadata__image',
                id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
                externalId: undefined,
                name: 'OG:Image',
                required: false,
                type: 'asset',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Title (text)
             */
            open_graph_metadata__title: {
                codename: 'open_graph_metadata__title',
                id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
                externalId: undefined,
                name: 'OG:Title',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Type (text)
             */
            open_graph_metadata__type: {
                codename: 'open_graph_metadata__type',
                id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
                externalId: undefined,
                name: 'OG:Type',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * Overview (rich_text)
             */
            overview: {
                codename: 'overview',
                id: '27b224b5-ce97-456f-9da6-8556e4c2fd88',
                externalId: undefined,
                name: 'Overview',
                required: false,
                type: 'rich_text'
            },

            /**
             * Robots Follow (multiple_choice)
             */
            seo_metadata__robots_follow: {
                codename: 'seo_metadata__robots_follow',
                id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
                externalId: undefined,
                name: 'Robots Follow',
                required: false,
                type: 'multiple_choice',
                options: {
                    follow: {
                        name: 'Follow',
                        id: 'b1093b4b-2a6e-4698-affc-86fa0d30dc29',
                        codename: 'follow',
                        externalId: undefined
                    },
                    no_follow: {
                        name: 'No Follow',
                        id: 'ea97e348-ba05-4508-98a5-97d6513735b5',
                        codename: 'no_follow',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Robots Index (multiple_choice)
             */
            seo_metadata__robots_index: {
                codename: 'seo_metadata__robots_index',
                id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
                externalId: undefined,
                name: 'Robots Index',
                required: false,
                type: 'multiple_choice',
                options: {
                    index: {
                        name: 'Index',
                        id: 'a526485d-4693-42f7-954c-62c8fc091674',
                        codename: 'index',
                        externalId: undefined
                    },
                    no_index: {
                        name: 'No Index',
                        id: 'f71db495-aa77-4291-b1fc-7f0818faef52',
                        codename: 'no_index',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Slug (url_slug)
             */
            url: {
                codename: 'url',
                id: '8f627d96-9b8d-4fe9-b437-38e4b15ccc8b',
                externalId: undefined,
                name: 'Slug',
                required: false,
                type: 'url_slug'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '529c72d2-92a1-4aba-bb27-19f3d0b71bb5',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            },

            /**
             * Title (text)
             *
             * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
             */
            seo_metadata__title: {
                codename: 'seo_metadata__title',
                id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Why us (modular_content)
             */
            why_us: {
                codename: 'why_us',
                id: 'ee5dcb35-32ab-455b-b719-8f4ff98caeb3',
                externalId: undefined,
                name: 'Why us',
                required: false,
                type: 'modular_content'
            }
        }
    },

    /**
     * Course Listing
     */
    course_listing: {
        codename: 'course_listing',
        id: '9a07c109-a78c-487a-b842-1189bf17628f',
        externalId: undefined,
        name: 'Course Listing',
        elements: {
            /**
             * Course category (taxonomy)
             */
            course_category: {
                codename: 'course_category',
                id: 'c3d02bcd-1411-49a5-a633-3d7eb656ef55',
                externalId: undefined,
                name: 'Course category',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'd0955938-8542-419e-a86b-6ca398e6a8b8',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Event
     */
    event: {
        codename: 'event',
        id: '7c61f0d7-5790-41a8-99d3-6b88063e95c3',
        externalId: undefined,
        name: 'Event',
        elements: {
            /**
             * Canonical URL (text)
             */
            seo_metadata__canonical_url: {
                codename: 'seo_metadata__canonical_url',
                id: '145b30b0-1438-4e27-998f-c37a23c39393',
                externalId: undefined,
                name: 'Canonical URL',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Channels (taxonomy)
             */
            channels: {
                codename: 'channels',
                id: '5403ad6f-f5b1-4745-a735-57eb50c82109',
                externalId: undefined,
                name: 'Channels',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Content (rich_text)
             */
            content: {
                codename: 'content',
                id: '77dea97f-80a0-47fa-a4f7-9c065dde884a',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'rich_text'
            },

            /**
             * Description (text)
             *
             * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
             */
            seo_metadata__description: {
                codename: 'seo_metadata__description',
                id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * End date time (date_time)
             */
            end_date_time: {
                codename: 'end_date_time',
                id: 'a39299ad-ce80-4ac3-9eca-af669b8fa88e',
                externalId: undefined,
                name: 'End date/time',
                required: false,
                type: 'date_time'
            },

            /**
             * Event location (text)
             */
            event_location: {
                codename: 'event_location',
                id: '67b28b12-119e-41be-bcfa-a94a3f62ab2b',
                externalId: undefined,
                name: 'Event location',
                required: false,
                type: 'text'
            },

            /**
             * Event name (text)
             */
            title: {
                codename: 'title',
                id: '60505805-3b06-41a6-9e5f-49094763c4a2',
                externalId: undefined,
                name: 'Event name',
                required: true,
                type: 'text'
            },

            /**
             * Event Type (taxonomy)
             */
            event_type: {
                codename: 'event_type',
                id: '22e0f9d8-14cc-49a3-b443-3d150c49f7dd',
                externalId: undefined,
                name: 'Event Type',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Keywords (text)
             */
            seo_metadata__keywords: {
                codename: 'seo_metadata__keywords',
                id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
                externalId: undefined,
                name: 'Keywords',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * OG Description (text)
             */
            open_graph_metadata__description: {
                codename: 'open_graph_metadata__description',
                id: '3886ee4b-3434-4587-9aab-d54793e1075f',
                externalId: undefined,
                name: 'OG:Description',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Image (asset)
             *
             * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
             */
            open_graph_metadata__image: {
                codename: 'open_graph_metadata__image',
                id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
                externalId: undefined,
                name: 'OG:Image',
                required: false,
                type: 'asset',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Title (text)
             */
            open_graph_metadata__title: {
                codename: 'open_graph_metadata__title',
                id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
                externalId: undefined,
                name: 'OG:Title',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Type (text)
             */
            open_graph_metadata__type: {
                codename: 'open_graph_metadata__type',
                id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
                externalId: undefined,
                name: 'OG:Type',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * Organiser (text)
             */
            organiser: {
                codename: 'organiser',
                id: '34a16dec-5696-40fd-8fb9-f3b9d5133815',
                externalId: undefined,
                name: 'Organiser',
                required: false,
                type: 'text'
            },

            /**
             * Robots Follow (multiple_choice)
             */
            seo_metadata__robots_follow: {
                codename: 'seo_metadata__robots_follow',
                id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
                externalId: undefined,
                name: 'Robots Follow',
                required: false,
                type: 'multiple_choice',
                options: {
                    follow: {
                        name: 'Follow',
                        id: 'b1093b4b-2a6e-4698-affc-86fa0d30dc29',
                        codename: 'follow',
                        externalId: undefined
                    },
                    no_follow: {
                        name: 'No Follow',
                        id: 'ea97e348-ba05-4508-98a5-97d6513735b5',
                        codename: 'no_follow',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Robots Index (multiple_choice)
             */
            seo_metadata__robots_index: {
                codename: 'seo_metadata__robots_index',
                id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
                externalId: undefined,
                name: 'Robots Index',
                required: false,
                type: 'multiple_choice',
                options: {
                    index: {
                        name: 'Index',
                        id: 'a526485d-4693-42f7-954c-62c8fc091674',
                        codename: 'index',
                        externalId: undefined
                    },
                    no_index: {
                        name: 'No Index',
                        id: 'f71db495-aa77-4291-b1fc-7f0818faef52',
                        codename: 'no_index',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Start date time (date_time)
             */
            start_date_time: {
                codename: 'start_date_time',
                id: '07419dda-3ede-477b-a8d5-3f4ea57aaf39',
                externalId: undefined,
                name: 'Start date/time',
                required: true,
                type: 'date_time'
            },

            /**
             * Title (text)
             *
             * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
             */
            seo_metadata__title: {
                codename: 'seo_metadata__title',
                id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * URL (url_slug)
             */
            url: {
                codename: 'url',
                id: '34ae9ec7-8e7e-4582-850a-6c20090c7ab0',
                externalId: undefined,
                name: 'URL',
                required: false,
                type: 'url_slug'
            }
        }
    },

    /**
     * Event Listing
     */
    event_listing: {
        codename: 'event_listing',
        id: '37064205-60e7-4f6e-8154-7a9e12d350e1',
        externalId: undefined,
        name: 'Event Listing',
        elements: {
            /**
             * Event Type (taxonomy)
             */
            event_type: {
                codename: 'event_type',
                id: '389b37f1-39a1-430a-929c-23746beb51e7',
                externalId: undefined,
                name: 'Event Type',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '007ee0ab-da95-46c7-91b6-a1eef896bacd',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * FAQ
     */
    faq: {
        codename: 'faq',
        id: '44e0a36e-2ff4-4e53-85da-21efc87e58e7',
        externalId: undefined,
        name: 'FAQ',
        elements: {
            /**
             * Answer (rich_text)
             */
            answer: {
                codename: 'answer',
                id: '7f90c20c-375e-4826-b3aa-de7e38d98b42',
                externalId: undefined,
                name: 'Answer',
                required: false,
                type: 'rich_text'
            },

            /**
             * Question (text)
             */
            question: {
                codename: 'question',
                id: '68930750-475f-4793-8c74-30688769fc50',
                externalId: undefined,
                name: 'Question',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Footer
     */
    footer: {
        codename: 'footer',
        id: '036b48b0-4e5f-4e2c-a11a-824333e6cfce',
        externalId: undefined,
        name: 'Footer',
        elements: {
            /**
             * Copyright notice (text)
             */
            copyright_notice: {
                codename: 'copyright_notice',
                id: '7fb7bfa2-e730-4e98-8ecd-9393ea219f26',
                externalId: undefined,
                name: 'Copyright notice',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Form  Hubspot integration
     */
    form: {
        codename: 'form',
        id: '72ae336f-85d3-48c6-84da-0450a93c8c8b',
        externalId: undefined,
        name: 'Form (Hubspot integration)',
        elements: {
            /**
             * Form (custom)
             */
            form: {
                codename: 'form',
                id: 'db7dcc9b-a179-44f2-ab48-18d679a770be',
                externalId: undefined,
                name: 'Form',
                required: false,
                type: 'custom'
            }
        }
    },

    /**
     * Hero Unit
     */
    hero_unit: {
        codename: 'hero_unit',
        id: '0a455385-90a1-4ccc-88af-ce9abd6c07a4',
        externalId: undefined,
        name: 'Hero Unit',
        elements: {
            /**
             * Background image (asset)
             */
            background_image: {
                codename: 'background_image',
                id: '8e3aa740-0f46-4827-bd01-6752557b37dd',
                externalId: undefined,
                name: 'Background image',
                required: false,
                type: 'asset'
            },

            /**
             * Call to Action (modular_content)
             */
            call_to_action: {
                codename: 'call_to_action',
                id: 'dfd3a2da-b0a2-49af-8c25-f96fb47bbff7',
                externalId: undefined,
                name: 'Call to Action',
                required: false,
                type: 'modular_content'
            },

            /**
             * Content (rich_text)
             */
            content: {
                codename: 'content',
                id: '99ebe8aa-7069-431f-b258-05900a9c11d6',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'rich_text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'dbf21840-7f55-4f14-a926-05ee07a98118',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Image Container
     */
    image_container: {
        codename: 'image_container',
        id: '6ebb749b-5eaf-44f6-8a5e-268921144349',
        externalId: undefined,
        name: 'Image Container',
        elements: {
            /**
             * Content (rich_text)
             */
            content: {
                codename: 'content',
                id: 'fb8a6471-ce6b-446b-8034-19c921ee5683',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'rich_text'
            },

            /**
             * Heading (text)
             */
            heading: {
                codename: 'heading',
                id: '9cd23f04-c571-4ebd-86e0-11f3ad6503d7',
                externalId: undefined,
                name: 'Heading',
                required: false,
                type: 'text'
            },

            /**
             * Image (asset)
             */
            image: {
                codename: 'image',
                id: '569f29a5-57c5-49ef-a120-5f4931d34acf',
                externalId: undefined,
                name: 'Image',
                required: false,
                type: 'asset'
            },

            /**
             * Image location (multiple_choice)
             */
            image_location: {
                codename: 'image_location',
                id: 'a537365b-e81b-4f70-b34b-de4f63e26815',
                externalId: undefined,
                name: 'Image location',
                required: false,
                type: 'multiple_choice',
                options: {
                    left: {
                        name: 'Left',
                        id: '47851e45-3208-4cdd-a090-61231fbf90b5',
                        codename: 'left',
                        externalId: undefined
                    },
                    right: {
                        name: 'Right',
                        id: 'ae997d79-0bf5-4c44-b7f0-205c1b7e1212',
                        codename: 'right',
                        externalId: undefined
                    }
                }
            }
        }
    },

    /**
     * Milestone
     */
    milestone: {
        codename: 'milestone',
        id: '1df5b589-13e7-4331-bbdd-761bd6255cdc',
        externalId: undefined,
        name: 'Milestone',
        elements: {
            /**
             * Icon  optional  (asset)
             */
            icon__optional_: {
                codename: 'icon__optional_',
                id: '4b497516-12f3-4bd2-a3fb-bc4120fb808e',
                externalId: undefined,
                name: 'Icon (optional)',
                required: false,
                type: 'asset'
            },

            /**
             * Subtitle (text)
             */
            subtitle: {
                codename: 'subtitle',
                id: '9e57f001-a7da-467a-a194-a58ddfc28628',
                externalId: undefined,
                name: 'Subtitle',
                required: true,
                type: 'text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '1c5cdfbb-69c4-4b9b-83c8-8992d5407c2d',
                externalId: undefined,
                name: 'Title',
                required: true,
                type: 'text'
            }
        }
    },

    /**
     * Milestone Listing
     */
    milestone_listing: {
        codename: 'milestone_listing',
        id: '477fe0bd-c927-4e31-a3f2-f14c17dc2c38',
        externalId: undefined,
        name: 'Milestone Listing',
        elements: {
            /**
             * Milestones (modular_content)
             */
            grid_items: {
                codename: 'grid_items',
                id: '8351781d-29fc-40e3-8224-ce65c22f29f6',
                externalId: undefined,
                name: 'Milestones',
                required: false,
                type: 'modular_content'
            }
        }
    },

    /**
     * Panel
     */
    _panel: {
        codename: '_panel',
        id: 'cd495da0-4247-4456-8d83-288a777f6c23',
        externalId: undefined,
        name: 'Panel',
        elements: {
            /**
             * Blurb (text)
             */
            blurb: {
                codename: 'blurb',
                id: '972b7b5b-348d-4983-be0b-084f53bd8f6a',
                externalId: undefined,
                name: 'Blurb',
                required: false,
                type: 'text'
            },

            /**
             * Heading (text)
             */
            heading: {
                codename: 'heading',
                id: '83ec6bbc-0271-416b-9dad-188c825b39a9',
                externalId: undefined,
                name: 'Heading',
                required: false,
                type: 'text'
            },

            /**
             * Image (asset)
             */
            image: {
                codename: 'image',
                id: '0c947609-33fc-49d4-8d89-fea08403a503',
                externalId: undefined,
                name: 'Image',
                required: false,
                type: 'asset'
            },

            /**
             * Link (text)
             */
            link: {
                codename: 'link',
                id: '168fecf2-6821-49e9-9e92-9abfc462a61e',
                externalId: undefined,
                name: 'Link',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Panel Listing
     */
    panel_listing: {
        codename: 'panel_listing',
        id: '507ad995-6abb-48a7-b3cf-df8fe45ff8ff',
        externalId: undefined,
        name: 'Panel Listing',
        elements: {
            /**
             * Heading (text)
             */
            heading: {
                codename: 'heading',
                id: '825bd606-122b-425e-8403-4beb79181ada',
                externalId: undefined,
                name: 'Heading',
                required: false,
                type: 'text'
            },

            /**
             * Orientation (multiple_choice)
             */
            orientation: {
                codename: 'orientation',
                id: '085d12ae-8b7e-4086-87fa-89b47ec442d0',
                externalId: undefined,
                name: 'Orientation',
                required: true,
                type: 'multiple_choice',
                options: {
                    horizontal: {
                        name: 'Horizontal',
                        id: '0ea8fb7b-6103-4bce-aa56-21a4ee08e79c',
                        codename: 'horizontal',
                        externalId: undefined
                    },
                    vertical: {
                        name: 'Vertical',
                        id: '19ada33a-d0e1-4491-b356-1c62e725dca6',
                        codename: 'vertical',
                        externalId: undefined
                    }
                }
            },

            /**
             * Panels (modular_content)
             */
            panels: {
                codename: 'panels',
                id: 'f77bc4f3-3619-4b19-a32b-f2e282f48e11',
                externalId: undefined,
                name: 'Panels',
                required: false,
                type: 'modular_content'
            }
        }
    },

    /**
     * Person
     */
    person: {
        codename: 'person',
        id: '8f37c482-5457-417b-8c61-7e28a8035cf0',
        externalId: undefined,
        name: 'Person',
        elements: {
            /**
             * Bio (rich_text)
             */
            bio: {
                codename: 'bio',
                id: '962a1f4a-57f2-4cd2-bf5c-8d25aca7f932',
                externalId: undefined,
                name: 'Bio',
                required: false,
                type: 'rich_text'
            },

            /**
             * First name (text)
             */
            first_name: {
                codename: 'first_name',
                id: '0e288622-5bd2-406b-a770-a950a115f314',
                externalId: undefined,
                name: 'First name',
                required: false,
                type: 'text'
            },

            /**
             * Last name (text)
             */
            last_name: {
                codename: 'last_name',
                id: '367814b8-8c12-48af-b248-d92cb132583f',
                externalId: undefined,
                name: 'Last name',
                required: false,
                type: 'text'
            },

            /**
             * Occupation (text)
             */
            occupation: {
                codename: 'occupation',
                id: '233c304b-3558-4fc2-b077-d44a7fd3cbb2',
                externalId: undefined,
                name: 'Occupation',
                required: false,
                type: 'text'
            },

            /**
             * Photograph (asset)
             */
            photograph: {
                codename: 'photograph',
                id: '34213e8b-f1e7-455b-9da6-28a73bf5c688',
                externalId: undefined,
                name: 'Photograph',
                required: false,
                type: 'asset'
            }
        }
    },

    /**
     * Product
     */
    product: {
        codename: 'product',
        id: '62fcbb78-ab65-4247-99cc-e29bb789133d',
        externalId: undefined,
        name: 'Product',
        elements: {
            /**
             * Body (rich_text)
             */
            body: {
                codename: 'body',
                id: '10e3b6eb-79f4-48d9-8b73-e8d7b6ccf9f0',
                externalId: undefined,
                name: 'Body',
                required: false,
                type: 'rich_text'
            },

            /**
             * Canonical URL (text)
             */
            seo_metadata__canonical_url: {
                codename: 'seo_metadata__canonical_url',
                id: '145b30b0-1438-4e27-998f-c37a23c39393',
                externalId: undefined,
                name: 'Canonical URL',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Channels (taxonomy)
             */
            channel: {
                codename: 'channel',
                id: '8b555b23-055c-4cd1-91fc-016e53f87146',
                externalId: undefined,
                name: 'Channel',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Description (rich_text)
             */
            description: {
                codename: 'description',
                id: '59322205-f074-402c-9871-334cdcf5c4e1',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'rich_text'
            },

            /**
             * Description (text)
             *
             * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
             */
            seo_metadata__description: {
                codename: 'seo_metadata__description',
                id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Keywords (text)
             */
            seo_metadata__keywords: {
                codename: 'seo_metadata__keywords',
                id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
                externalId: undefined,
                name: 'Keywords',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            },

            /**
             * Model (text)
             */
            model: {
                codename: 'model',
                id: '822ab7f4-abe0-44e5-b48d-e463d9a5bc97',
                externalId: undefined,
                name: 'Model',
                required: false,
                type: 'text'
            },

            /**
             * OG Description (text)
             */
            open_graph_metadata__description: {
                codename: 'open_graph_metadata__description',
                id: '3886ee4b-3434-4587-9aab-d54793e1075f',
                externalId: undefined,
                name: 'OG:Description',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Image (asset)
             *
             * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
             */
            open_graph_metadata__image: {
                codename: 'open_graph_metadata__image',
                id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
                externalId: undefined,
                name: 'OG:Image',
                required: false,
                type: 'asset',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Title (text)
             */
            open_graph_metadata__title: {
                codename: 'open_graph_metadata__title',
                id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
                externalId: undefined,
                name: 'OG:Title',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * OG Type (text)
             */
            open_graph_metadata__type: {
                codename: 'open_graph_metadata__type',
                id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
                externalId: undefined,
                name: 'OG:Type',
                required: false,
                type: 'text',

                snippetCodename: 'open_graph_metadata'
            },

            /**
             * Price (number)
             */
            price: {
                codename: 'price',
                id: '8147b730-1174-440f-b66c-3c7052a27c13',
                externalId: undefined,
                name: 'Price',
                required: false,
                type: 'number'
            },

            /**
             * Product category (taxonomy)
             */
            product_category: {
                codename: 'product_category',
                id: '9cb23fa0-7975-40f3-9b2e-284566ed5610',
                externalId: undefined,
                name: 'Product category',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Product image (asset)
             */
            product_image: {
                codename: 'product_image',
                id: 'ef97bfab-e78d-462a-9a10-092f5dbc133e',
                externalId: undefined,
                name: 'Product image',
                required: false,
                type: 'asset'
            },

            /**
             * Robots Follow (multiple_choice)
             */
            seo_metadata__robots_follow: {
                codename: 'seo_metadata__robots_follow',
                id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
                externalId: undefined,
                name: 'Robots Follow',
                required: false,
                type: 'multiple_choice',
                options: {
                    follow: {
                        name: 'Follow',
                        id: 'b1093b4b-2a6e-4698-affc-86fa0d30dc29',
                        codename: 'follow',
                        externalId: undefined
                    },
                    no_follow: {
                        name: 'No Follow',
                        id: 'ea97e348-ba05-4508-98a5-97d6513735b5',
                        codename: 'no_follow',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * Robots Index (multiple_choice)
             */
            seo_metadata__robots_index: {
                codename: 'seo_metadata__robots_index',
                id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
                externalId: undefined,
                name: 'Robots Index',
                required: false,
                type: 'multiple_choice',
                options: {
                    index: {
                        name: 'Index',
                        id: 'a526485d-4693-42f7-954c-62c8fc091674',
                        codename: 'index',
                        externalId: undefined
                    },
                    no_index: {
                        name: 'No Index',
                        id: 'f71db495-aa77-4291-b1fc-7f0818faef52',
                        codename: 'no_index',
                        externalId: undefined
                    }
                },
                snippetCodename: 'seo_metadata'
            },

            /**
             * SKU (text)
             */
            sku: {
                codename: 'sku',
                id: '89b5849d-c60a-4a06-9c02-d4dcd74ef692',
                externalId: undefined,
                name: 'SKU',
                required: false,
                type: 'text'
            },

            /**
             * Slug (url_slug)
             */
            url: {
                codename: 'url',
                id: '93ac7a11-2b9f-410c-9ce7-9d95e90b0960',
                externalId: undefined,
                name: 'Slug',
                required: false,
                type: 'url_slug'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '11b1fdeb-c495-4b26-9004-7eb7d1cc1fef',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            },

            /**
             * Title (text)
             *
             * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
             */
            seo_metadata__title: {
                codename: 'seo_metadata__title',
                id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text',

                snippetCodename: 'seo_metadata'
            }
        }
    },

    /**
     * Product Listing
     */
    product_listing: {
        codename: 'product_listing',
        id: '18b3b0be-6bd3-47a8-8edb-7d4708089ce2',
        externalId: undefined,
        name: 'Product Listing',
        elements: {
            /**
             * Product category (taxonomy)
             */
            product_category: {
                codename: 'product_category',
                id: '675d419a-5bab-4483-88c1-8fb9c09f991a',
                externalId: undefined,
                name: 'Product category',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '151600b5-f75c-456e-9e56-ac43cea763ad',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Robots txt
     */
    robots_txt: {
        codename: 'robots_txt',
        id: '73c0aa87-131e-459c-bdcd-0d4942d16c85',
        externalId: undefined,
        name: 'Robots.txt',
        elements: {
            /**
             * Content (text)
             */
            content: {
                codename: 'content',
                id: 'ba26d3a5-9f88-422e-bcb5-4b9bc85a85e2',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Site Configuration
     */
    site_configuration: {
        codename: 'site_configuration',
        id: '971ded8c-469f-476d-b7c4-716842db4027',
        externalId: undefined,
        name: 'Site Configuration',
        elements: {
            /**
             * Translation (custom)
             */
            translation: {
                codename: 'translation',
                id: '1fd5cae8-cd8a-46fd-80f4-18c92897d543',
                externalId: undefined,
                name: 'Translation',
                required: false,
                type: 'custom'
            }
        }
    },

    /**
     * Testimonial
     */
    testimonial: {
        codename: 'testimonial',
        id: 'd30689be-9900-4d54-a549-e919346f7990',
        externalId: undefined,
        name: 'Testimonial',
        elements: {
            /**
             * Author (modular_content)
             */
            author: {
                codename: 'author',
                id: 'f60caa40-5a31-47e8-9e3c-be862631381c',
                externalId: undefined,
                name: 'Author',
                required: false,
                type: 'modular_content'
            },

            /**
             * Quote (text)
             */
            quote: {
                codename: 'quote',
                id: 'b0a76be2-49f9-44d0-a565-bf61f70f0c93',
                externalId: undefined,
                name: 'Quote',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * YouTube Embed
     */
    youtube_embed: {
        codename: 'youtube_embed',
        id: '269c7ce3-1d74-41cd-bd35-2d5530aab4b3',
        externalId: undefined,
        name: 'YouTube Embed',
        elements: {
            /**
             * Autoplay (multiple_choice)
             */
            autoplay: {
                codename: 'autoplay',
                id: 'd59de605-0b0a-4e6f-9758-236a8cda250f',
                externalId: undefined,
                name: 'Autoplay',
                required: false,
                type: 'multiple_choice',
                options: {
                    yes: {
                        name: 'Yes',
                        id: '5f576ac4-7842-48ab-864b-d98ea5420ea9',
                        codename: 'yes',
                        externalId: undefined
                    },
                    no: {
                        name: 'No',
                        id: '324d11dd-f0ac-4a0b-9074-1d6068fec86d',
                        codename: 'no',
                        externalId: undefined
                    }
                }
            },

            /**
             * Body (rich_text)
             */
            body: {
                codename: 'body',
                id: 'a2b286f6-be90-4ba4-83b7-fd217b1cecfb',
                externalId: undefined,
                name: 'Body',
                required: false,
                type: 'rich_text'
            },

            /**
             * End time (number)
             *
             * Time in seconds, so if you want to end the video at 1:30 you fill in 90
             */
            end_time: {
                codename: 'end_time',
                id: '7b78f5bf-8fe1-4fb2-ac57-32f9058862c7',
                externalId: undefined,
                name: 'End time',
                required: false,
                type: 'number'
            },

            /**
             * Image (asset)
             */
            image: {
                codename: 'image',
                id: '22365200-26af-4dd7-a41b-23f2807dca56',
                externalId: undefined,
                name: 'Image',
                required: false,
                type: 'asset'
            },

            /**
             * Start time (number)
             *
             * Time in seconds, so if you want to end the video at 1:30 you fill in 90
             */
            start_time: {
                codename: 'start_time',
                id: '54a9d1b9-98bb-4e62-8b7c-f3a55d82f701',
                externalId: undefined,
                name: 'Start time',
                required: false,
                type: 'number'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'e5b3b337-e250-47a6-a5f7-7dfd8cccd6fd',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            },

            /**
             * YouTube (custom)
             */
            youtube: {
                codename: 'youtube',
                id: '216caf7c-b592-4517-ae81-54fa69fa2d1f',
                externalId: undefined,
                name: 'YouTube',
                required: true,
                type: 'custom'
            }
        }
    }
} as const;
