/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: ⚒ Karma Manufacturing
 * Environment: Production
 * Project Id: a917b5bf-e2e1-011e-0a73-0b317b1e1c33
 */
export const contentTypes = {
  /**
   * 💡 Page
   */
  page: {
    codename: 'page',
    id: '5aab1bd3-9433-40d2-8e0f-cbda835ec5fd',
    externalId: undefined,
    name: '💡 Page',
    elements: {
      /**
       * Canonical URL (text)
       */
      seo_metadata__canonical_url: {
        codename: 'seo_metadata__canonical_url',
        id: '145b30b0-1438-4e27-998f-c37a23c39393',
        externalId: undefined,
        name: 'Canonical URL',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '756bc39a-7d70-4faa-9116-eeacd689ff4f',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       *
       * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
        externalId: undefined,
        name: 'Keywords',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Navigation Structures (taxonomy)
       */
      navigation_structures: {
        codename: 'navigation_structures',
        id: '943b2571-e126-47ae-814e-179b78aad2f7',
        externalId: undefined,
        name: 'Navigation Structures',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * OG:Description (text)
       */
      open_graph_metadata__description: {
        codename: 'open_graph_metadata__description',
        id: '3886ee4b-3434-4587-9aab-d54793e1075f',
        externalId: undefined,
        name: 'OG:Description',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Image (asset)
       *
       * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
       */
      open_graph_metadata__image: {
        codename: 'open_graph_metadata__image',
        id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
        externalId: undefined,
        name: 'OG:Image',
        required: false,
        type: 'asset',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Title (text)
       */
      open_graph_metadata__title: {
        codename: 'open_graph_metadata__title',
        id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
        externalId: undefined,
        name: 'OG:Title',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Type (text)
       */
      open_graph_metadata__type: {
        codename: 'open_graph_metadata__type',
        id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
        externalId: undefined,
        name: 'OG:Type',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * Robots Follow (multiple_choice)
       */
      seo_metadata__robots_follow: {
        codename: 'seo_metadata__robots_follow',
        id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
        externalId: undefined,
        name: 'Robots Follow',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Robots Index (multiple_choice)
       */
      seo_metadata__robots_index: {
        codename: 'seo_metadata__robots_index',
        id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
        externalId: undefined,
        name: 'Robots Index',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: '890cb2c8-fc22-4744-8965-0e8bfe284c62',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '93218af9-0226-422a-b1a0-27ad0058dcf4',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       *
       * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * URL (url_slug)
       */
      url: {
        codename: 'url',
        id: 'a1f23c97-017d-4764-bc39-82050166b371',
        externalId: undefined,
        name: 'URL',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 💡 Web Spotlight Root
   */
  web_spotlight_root: {
    codename: 'web_spotlight_root',
    id: '70a78305-2ef2-4f5d-9677-b01866e2f472',
    externalId: undefined,
    name: '💡 Web Spotlight Root',
    elements: {
      /**
       * Canonical URL (text)
       */
      seo_metadata__canonical_url: {
        codename: 'seo_metadata__canonical_url',
        id: '145b30b0-1438-4e27-998f-c37a23c39393',
        externalId: undefined,
        name: 'Canonical URL',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: 'cfacf602-c3a9-44d5-bafd-aea5af865ab9',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       *
       * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
        externalId: undefined,
        name: 'Keywords',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Logo (asset)
       */
      logo: {
        codename: 'logo',
        id: '5d7a0146-b986-4587-bf5c-3ba3111aa441',
        externalId: undefined,
        name: 'Logo',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Name (text)
       */
      name: {
        codename: 'name',
        id: 'd53ff95e-3ced-4a2f-9963-e640e6937a8b',
        externalId: undefined,
        name: 'Name',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * OG:Description (text)
       */
      open_graph_metadata__description: {
        codename: 'open_graph_metadata__description',
        id: '3886ee4b-3434-4587-9aab-d54793e1075f',
        externalId: undefined,
        name: 'OG:Description',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Image (asset)
       *
       * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
       */
      open_graph_metadata__image: {
        codename: 'open_graph_metadata__image',
        id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
        externalId: undefined,
        name: 'OG:Image',
        required: false,
        type: 'asset',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Title (text)
       */
      open_graph_metadata__title: {
        codename: 'open_graph_metadata__title',
        id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
        externalId: undefined,
        name: 'OG:Title',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Type (text)
       */
      open_graph_metadata__type: {
        codename: 'open_graph_metadata__type',
        id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
        externalId: undefined,
        name: 'OG:Type',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * Robots Follow (multiple_choice)
       */
      seo_metadata__robots_follow: {
        codename: 'seo_metadata__robots_follow',
        id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
        externalId: undefined,
        name: 'Robots Follow',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Robots Index (multiple_choice)
       */
      seo_metadata__robots_index: {
        codename: 'seo_metadata__robots_index',
        id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
        externalId: undefined,
        name: 'Robots Index',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: '68783b8a-a680-4d5e-aed1-5e136815f4ef',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Tagline (text)
       */
      tagline: {
        codename: 'tagline',
        id: '86c798ef-25ed-41e0-92c6-3b566161fd9d',
        externalId: undefined,
        name: 'Tagline',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'f66fd9c8-1894-4223-979a-0b829cb0ece2',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       *
       * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },
    },
  },

  /**
   * 📝 Trial
   */
  trial: {
    codename: 'trial',
    id: 'dfd8f840-843e-4231-8027-e089829812ae',
    externalId: undefined,
    name: '📝 Trial',
    elements: {
      /**
       * Company name (text)
       */
      company_name: {
        codename: 'company_name',
        id: '5364e864-36f6-48c3-8961-1b5e13513fc4',
        externalId: undefined,
        name: 'Company name',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Domain URL (text)
       */
      domain_url: {
        codename: 'domain_url',
        id: '450f4bdd-b696-49e6-af50-2786ee180f30',
        externalId: undefined,
        name: 'Domain URL',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Email address (text)
       */
      email_address: {
        codename: 'email_address',
        id: '24a9182d-af54-42a6-9048-230a255d44a0',
        externalId: undefined,
        name: 'Email address',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Environment ID (text)
       */
      environment_id: {
        codename: 'environment_id',
        id: 'cbbfda22-1c8c-4afb-9de1-06c17bc4d57a',
        externalId: undefined,
        name: 'Environment ID',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Log (text)
       */
      log: {
        codename: 'log',
        id: '7bbbf8d5-049e-4c0f-824a-def26347b368',
        externalId: undefined,
        name: 'Log',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * When started (date_time)
       */
      when_started: {
        codename: 'when_started',
        id: '5041a617-d683-4d02-8dd7-9ec62b896e30',
        externalId: undefined,
        name: 'When started',
        required: false,
        type: 'date_time',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Article
   */
  article: {
    codename: 'article',
    id: '5b4209c9-c672-459c-b8a2-43fd15fede54',
    externalId: undefined,
    name: 'Article',
    elements: {
      /**
       * Abstract (text)
       */
      abstract: {
        codename: 'abstract',
        id: 'bf77669f-5020-4cb7-9342-b9de30afdd77',
        externalId: undefined,
        name: 'Abstract',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Article Category (taxonomy)
       */
      article_type: {
        codename: 'article_type',
        id: '2cf6d39e-b61c-4df1-a390-b267b1293f56',
        externalId: undefined,
        name: 'Article type',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Author (modular_content)
       */
      author: {
        codename: 'author',
        id: '9611446a-69b1-44d5-b7c1-9cbd7fa5151a',
        externalId: undefined,
        name: 'Author',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Canonical URL (text)
       */
      seo_metadata__canonical_url: {
        codename: 'seo_metadata__canonical_url',
        id: '145b30b0-1438-4e27-998f-c37a23c39393',
        externalId: undefined,
        name: 'Canonical URL',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '0746ed7f-f75c-427c-85da-70a71cd14958',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       *
       * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Hero Image (asset)
       */
      hero_image: {
        codename: 'hero_image',
        id: '0ba20928-908d-48ca-b326-5f0f2fff663d',
        externalId: undefined,
        name: 'Hero Image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
        externalId: undefined,
        name: 'Keywords',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * OG:Description (text)
       */
      open_graph_metadata__description: {
        codename: 'open_graph_metadata__description',
        id: '3886ee4b-3434-4587-9aab-d54793e1075f',
        externalId: undefined,
        name: 'OG:Description',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Image (asset)
       *
       * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
       */
      open_graph_metadata__image: {
        codename: 'open_graph_metadata__image',
        id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
        externalId: undefined,
        name: 'OG:Image',
        required: false,
        type: 'asset',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Title (text)
       */
      open_graph_metadata__title: {
        codename: 'open_graph_metadata__title',
        id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
        externalId: undefined,
        name: 'OG:Title',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Type (text)
       */
      open_graph_metadata__type: {
        codename: 'open_graph_metadata__type',
        id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
        externalId: undefined,
        name: 'OG:Type',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * Publishing date (date_time)
       */
      publishing_date: {
        codename: 'publishing_date',
        id: '99460d45-bd27-480b-b2f5-5ae45c554488',
        externalId: undefined,
        name: 'Publishing date',
        required: false,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Robots Follow (multiple_choice)
       */
      seo_metadata__robots_follow: {
        codename: 'seo_metadata__robots_follow',
        id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
        externalId: undefined,
        name: 'Robots Follow',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Robots Index (multiple_choice)
       */
      seo_metadata__robots_index: {
        codename: 'seo_metadata__robots_index',
        id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
        externalId: undefined,
        name: 'Robots Index',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'd92a08b1-2bb1-4880-9dcd-40add106e7c4',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       *
       * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * URL (url_slug)
       */
      url: {
        codename: 'url',
        id: 'a9a2ddec-60e0-435e-8cf5-94fe50669640',
        externalId: undefined,
        name: 'URL',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Article Listing
   */
  article_listing: {
    codename: 'article_listing',
    id: 'a967cfb4-ce15-4a22-b6e7-a9bf632fbd2b',
    externalId: undefined,
    name: 'Article Listing',
    elements: {
      /**
       * Article Category (taxonomy)
       */
      article_type: {
        codename: 'article_type',
        id: '161367e7-e60f-494c-a130-b497e358a876',
        externalId: undefined,
        name: 'Article type',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'a210727c-e09d-44c0-ba89-908870ece3c0',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Call to Action
   */
  call_to_action: {
    codename: 'call_to_action',
    id: '068970e2-e5ba-44be-8bc4-66acb19547f1',
    externalId: undefined,
    name: 'Call to Action',
    elements: {
      /**
       * Item Target (modular_content)
       */
      item_target: {
        codename: 'item_target',
        id: '513c3019-0fbc-4e4c-9ef5-bc37b7f70dee',
        externalId: undefined,
        name: 'Item Target',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Manual Target (text)
       */
      manual_target: {
        codename: 'manual_target',
        id: '03b11077-1053-44dd-8047-c1119d0b393a',
        externalId: undefined,
        name: 'Manual Target',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'f23fb051-8fdb-4067-b02b-5b4313ceaa06',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Carousel
   */
  carousel: {
    codename: 'carousel',
    id: 'd3157a0b-928c-4c69-b3d5-8816e9e8e406',
    externalId: undefined,
    name: 'Carousel',
    elements: {
      /**
       * Elements (modular_content)
       */
      elements: {
        codename: 'elements',
        id: '0c889cf7-b807-4a92-80bc-c0e500d8f1b5',
        externalId: undefined,
        name: 'Elements',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Content Chunk
   */
  content_chunk: {
    codename: 'content_chunk',
    id: 'feaac754-fe8a-499d-af52-a7db0bb65499',
    externalId: undefined,
    name: 'Content Chunk',
    elements: {
      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '243ad7ec-37bf-4152-a858-1a2cbdb144be',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Event
   */
  event: {
    codename: 'event',
    id: '7c61f0d7-5790-41a8-99d3-6b88063e95c3',
    externalId: undefined,
    name: 'Event',
    elements: {
      /**
       * Canonical URL (text)
       */
      seo_metadata__canonical_url: {
        codename: 'seo_metadata__canonical_url',
        id: '145b30b0-1438-4e27-998f-c37a23c39393',
        externalId: undefined,
        name: 'Canonical URL',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Channels (taxonomy)
       */
      channels: {
        codename: 'channels',
        id: '5403ad6f-f5b1-4745-a735-57eb50c82109',
        externalId: undefined,
        name: 'Channels',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '77dea97f-80a0-47fa-a4f7-9c065dde884a',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       *
       * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * End date/time (date_time)
       */
      end_date_time: {
        codename: 'end_date_time',
        id: 'a39299ad-ce80-4ac3-9eca-af669b8fa88e',
        externalId: undefined,
        name: 'End date/time',
        required: false,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Event location (text)
       */
      event_location: {
        codename: 'event_location',
        id: '67b28b12-119e-41be-bcfa-a94a3f62ab2b',
        externalId: undefined,
        name: 'Event location',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Event name (text)
       */
      title: {
        codename: 'title',
        id: '60505805-3b06-41a6-9e5f-49094763c4a2',
        externalId: undefined,
        name: 'Event name',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Event Type (taxonomy)
       */
      event_type: {
        codename: 'event_type',
        id: '22e0f9d8-14cc-49a3-b443-3d150c49f7dd',
        externalId: undefined,
        name: 'Event Type',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
        externalId: undefined,
        name: 'Keywords',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * OG:Description (text)
       */
      open_graph_metadata__description: {
        codename: 'open_graph_metadata__description',
        id: '3886ee4b-3434-4587-9aab-d54793e1075f',
        externalId: undefined,
        name: 'OG:Description',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Image (asset)
       *
       * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
       */
      open_graph_metadata__image: {
        codename: 'open_graph_metadata__image',
        id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
        externalId: undefined,
        name: 'OG:Image',
        required: false,
        type: 'asset',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Title (text)
       */
      open_graph_metadata__title: {
        codename: 'open_graph_metadata__title',
        id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
        externalId: undefined,
        name: 'OG:Title',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Type (text)
       */
      open_graph_metadata__type: {
        codename: 'open_graph_metadata__type',
        id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
        externalId: undefined,
        name: 'OG:Type',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * Organiser (text)
       */
      organiser: {
        codename: 'organiser',
        id: '34a16dec-5696-40fd-8fb9-f3b9d5133815',
        externalId: undefined,
        name: 'Organiser',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Robots Follow (multiple_choice)
       */
      seo_metadata__robots_follow: {
        codename: 'seo_metadata__robots_follow',
        id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
        externalId: undefined,
        name: 'Robots Follow',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Robots Index (multiple_choice)
       */
      seo_metadata__robots_index: {
        codename: 'seo_metadata__robots_index',
        id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
        externalId: undefined,
        name: 'Robots Index',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Start date/time (date_time)
       */
      start_date_time: {
        codename: 'start_date_time',
        id: '07419dda-3ede-477b-a8d5-3f4ea57aaf39',
        externalId: undefined,
        name: 'Start date/time',
        required: true,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       *
       * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * URL (url_slug)
       */
      url: {
        codename: 'url',
        id: '34ae9ec7-8e7e-4582-850a-6c20090c7ab0',
        externalId: undefined,
        name: 'URL',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Event Listing
   */
  event_listing: {
    codename: 'event_listing',
    id: '37064205-60e7-4f6e-8154-7a9e12d350e1',
    externalId: undefined,
    name: 'Event Listing',
    elements: {
      /**
       * Event Type (taxonomy)
       */
      event_type: {
        codename: 'event_type',
        id: '389b37f1-39a1-430a-929c-23746beb51e7',
        externalId: undefined,
        name: 'Event Type',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '007ee0ab-da95-46c7-91b6-a1eef896bacd',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * FAQ
   */
  faq: {
    codename: 'faq',
    id: '44e0a36e-2ff4-4e53-85da-21efc87e58e7',
    externalId: undefined,
    name: 'FAQ',
    elements: {
      /**
       * Answer (rich_text)
       */
      answer: {
        codename: 'answer',
        id: '7f90c20c-375e-4826-b3aa-de7e38d98b42',
        externalId: undefined,
        name: 'Answer',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Question (text)
       */
      question: {
        codename: 'question',
        id: '68930750-475f-4793-8c74-30688769fc50',
        externalId: undefined,
        name: 'Question',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Footer
   */
  footer: {
    codename: 'footer',
    id: '036b48b0-4e5f-4e2c-a11a-824333e6cfce',
    externalId: undefined,
    name: 'Footer',
    elements: {
      /**
       * Copyright notice (text)
       */
      copyright_notice: {
        codename: 'copyright_notice',
        id: '7fb7bfa2-e730-4e98-8ecd-9393ea219f26',
        externalId: undefined,
        name: 'Copyright notice',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Form (Hubspot integration)
   */
  form: {
    codename: 'form',
    id: '72ae336f-85d3-48c6-84da-0450a93c8c8b',
    externalId: undefined,
    name: 'Form (Hubspot integration)',
    elements: {
      /**
       * Form (custom)
       */
      form: {
        codename: 'form',
        id: 'db7dcc9b-a179-44f2-ab48-18d679a770be',
        externalId: undefined,
        name: 'Form',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Hero Unit
   */
  hero_unit: {
    codename: 'hero_unit',
    id: '0a455385-90a1-4ccc-88af-ce9abd6c07a4',
    externalId: undefined,
    name: 'Hero Unit',
    elements: {
      /**
       * Background image (asset)
       */
      background_image: {
        codename: 'background_image',
        id: '8e3aa740-0f46-4827-bd01-6752557b37dd',
        externalId: undefined,
        name: 'Background image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Call to Action (modular_content)
       */
      call_to_action: {
        codename: 'call_to_action',
        id: 'dfd3a2da-b0a2-49af-8c25-f96fb47bbff7',
        externalId: undefined,
        name: 'Call to Action',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '99ebe8aa-7069-431f-b258-05900a9c11d6',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'dbf21840-7f55-4f14-a926-05ee07a98118',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Image Container
   */
  image_container: {
    codename: 'image_container',
    id: '6ebb749b-5eaf-44f6-8a5e-268921144349',
    externalId: undefined,
    name: 'Image Container',
    elements: {
      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: 'fb8a6471-ce6b-446b-8034-19c921ee5683',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Heading (text)
       */
      heading: {
        codename: 'heading',
        id: '9cd23f04-c571-4ebd-86e0-11f3ad6503d7',
        externalId: undefined,
        name: 'Heading',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Image (asset)
       */
      image: {
        codename: 'image',
        id: '569f29a5-57c5-49ef-a120-5f4931d34acf',
        externalId: undefined,
        name: 'Image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Image location (multiple_choice)
       */
      image_location: {
        codename: 'image_location',
        id: 'a537365b-e81b-4f70-b34b-de4f63e26815',
        externalId: undefined,
        name: 'Image location',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Milestone
   */
  milestone: {
    codename: 'milestone',
    id: '1df5b589-13e7-4331-bbdd-761bd6255cdc',
    externalId: undefined,
    name: 'Milestone',
    elements: {
      /**
       * Subtitle (text)
       */
      subtitle: {
        codename: 'subtitle',
        id: '9e57f001-a7da-467a-a194-a58ddfc28628',
        externalId: undefined,
        name: 'Subtitle',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '1c5cdfbb-69c4-4b9b-83c8-8992d5407c2d',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Milestone Listing
   */
  milestone_listing: {
    codename: 'milestone_listing',
    id: '477fe0bd-c927-4e31-a3f2-f14c17dc2c38',
    externalId: undefined,
    name: 'Milestone Listing',
    elements: {
      /**
       * Milestones (modular_content)
       */
      grid_items: {
        codename: 'grid_items',
        id: '8351781d-29fc-40e3-8224-ce65c22f29f6',
        externalId: undefined,
        name: 'Milestones',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Panel
   */
  _panel: {
    codename: '_panel',
    id: 'cd495da0-4247-4456-8d83-288a777f6c23',
    externalId: undefined,
    name: 'Panel',
    elements: {
      /**
       * Blurb (text)
       */
      blurb: {
        codename: 'blurb',
        id: '972b7b5b-348d-4983-be0b-084f53bd8f6a',
        externalId: undefined,
        name: 'Blurb',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Heading (text)
       */
      heading: {
        codename: 'heading',
        id: '83ec6bbc-0271-416b-9dad-188c825b39a9',
        externalId: undefined,
        name: 'Heading',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Image (asset)
       */
      image: {
        codename: 'image',
        id: '0c947609-33fc-49d4-8d89-fea08403a503',
        externalId: undefined,
        name: 'Image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Link (text)
       */
      link: {
        codename: 'link',
        id: '168fecf2-6821-49e9-9e92-9abfc462a61e',
        externalId: undefined,
        name: 'Link',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Panel Listing
   */
  panel_listing: {
    codename: 'panel_listing',
    id: '507ad995-6abb-48a7-b3cf-df8fe45ff8ff',
    externalId: undefined,
    name: 'Panel Listing',
    elements: {
      /**
       * Heading (text)
       */
      heading: {
        codename: 'heading',
        id: '825bd606-122b-425e-8403-4beb79181ada',
        externalId: undefined,
        name: 'Heading',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Orientation (multiple_choice)
       */
      orientation: {
        codename: 'orientation',
        id: '085d12ae-8b7e-4086-87fa-89b47ec442d0',
        externalId: undefined,
        name: 'Orientation',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Panels (modular_content)
       */
      panels: {
        codename: 'panels',
        id: 'f77bc4f3-3619-4b19-a32b-f2e282f48e11',
        externalId: undefined,
        name: 'Panels',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Person
   */
  person: {
    codename: 'person',
    id: '8f37c482-5457-417b-8c61-7e28a8035cf0',
    externalId: undefined,
    name: 'Person',
    elements: {
      /**
       * Bio (rich_text)
       */
      bio: {
        codename: 'bio',
        id: '962a1f4a-57f2-4cd2-bf5c-8d25aca7f932',
        externalId: undefined,
        name: 'Bio',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * First name (text)
       */
      first_name: {
        codename: 'first_name',
        id: '0e288622-5bd2-406b-a770-a950a115f314',
        externalId: undefined,
        name: 'First name',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Last name (text)
       */
      last_name: {
        codename: 'last_name',
        id: '367814b8-8c12-48af-b248-d92cb132583f',
        externalId: undefined,
        name: 'Last name',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Occupation (text)
       */
      occupation: {
        codename: 'occupation',
        id: '233c304b-3558-4fc2-b077-d44a7fd3cbb2',
        externalId: undefined,
        name: 'Occupation',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Photograph (asset)
       */
      photograph: {
        codename: 'photograph',
        id: '34213e8b-f1e7-455b-9da6-28a73bf5c688',
        externalId: undefined,
        name: 'Photograph',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Product
   */
  product: {
    codename: 'product',
    id: '62fcbb78-ab65-4247-99cc-e29bb789133d',
    externalId: undefined,
    name: 'Product',
    elements: {
      /**
       * Body (rich_text)
       */
      body: {
        codename: 'body',
        id: '10e3b6eb-79f4-48d9-8b73-e8d7b6ccf9f0',
        externalId: undefined,
        name: 'Body',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Canonical URL (text)
       */
      seo_metadata__canonical_url: {
        codename: 'seo_metadata__canonical_url',
        id: '145b30b0-1438-4e27-998f-c37a23c39393',
        externalId: undefined,
        name: 'Canonical URL',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Description (rich_text)
       */
      description: {
        codename: 'description',
        id: '59322205-f074-402c-9871-334cdcf5c4e1',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       *
       * Write a unique description for each pageTry to summarize content accuratelyAvoid generic descriptionsUse sentence caseCreate something click-worthy, not clickbaitMatch search intentInclude your target keyword where it makes sense
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '190b0bf9-f8c7-4ad8-be5f-844d2256d588',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: '681b8261-5d73-4ff5-a3e3-86f551ce631d',
        externalId: undefined,
        name: 'Keywords',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Model (text)
       */
      model: {
        codename: 'model',
        id: '822ab7f4-abe0-44e5-b48d-e463d9a5bc97',
        externalId: undefined,
        name: 'Model',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * OG:Description (text)
       */
      open_graph_metadata__description: {
        codename: 'open_graph_metadata__description',
        id: '3886ee4b-3434-4587-9aab-d54793e1075f',
        externalId: undefined,
        name: 'OG:Description',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Image (asset)
       *
       * Ideally larger than 1200x630Ideal image aspect ratio: 1.91:1
       */
      open_graph_metadata__image: {
        codename: 'open_graph_metadata__image',
        id: 'c4f33233-4a38-46af-ae18-ebf534b615d4',
        externalId: undefined,
        name: 'OG:Image',
        required: false,
        type: 'asset',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Title (text)
       */
      open_graph_metadata__title: {
        codename: 'open_graph_metadata__title',
        id: 'e6a6aef9-44af-4f99-82ea-9ceee6f1d526',
        externalId: undefined,
        name: 'OG:Title',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * OG:Type (text)
       */
      open_graph_metadata__type: {
        codename: 'open_graph_metadata__type',
        id: '8042b550-cd5a-4149-8aed-b047a54dbc9c',
        externalId: undefined,
        name: 'OG:Type',
        required: false,
        type: 'text',
        snippetCodename: 'open_graph_metadata',
      },

      /**
       * Price (number)
       */
      price: {
        codename: 'price',
        id: '8147b730-1174-440f-b66c-3c7052a27c13',
        externalId: undefined,
        name: 'Price',
        required: false,
        type: 'number',
        snippetCodename: undefined,
      },

      /**
       * Product category (taxonomy)
       */
      product_category: {
        codename: 'product_category',
        id: '9cb23fa0-7975-40f3-9b2e-284566ed5610',
        externalId: undefined,
        name: 'Product category',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Product image (asset)
       */
      product_image: {
        codename: 'product_image',
        id: 'ef97bfab-e78d-462a-9a10-092f5dbc133e',
        externalId: undefined,
        name: 'Product image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Robots Follow (multiple_choice)
       */
      seo_metadata__robots_follow: {
        codename: 'seo_metadata__robots_follow',
        id: '59f3a9c8-2620-4ae2-9d8f-15f4afb0c30c',
        externalId: undefined,
        name: 'Robots Follow',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Robots Index (multiple_choice)
       */
      seo_metadata__robots_index: {
        codename: 'seo_metadata__robots_index',
        id: '55ca45b3-a719-42da-b2a4-3f38942a70b7',
        externalId: undefined,
        name: 'Robots Index',
        required: false,
        type: 'multiple_choice',
        snippetCodename: 'seo_metadata',
      },

      /**
       * SKU (text)
       */
      sku: {
        codename: 'sku',
        id: '89b5849d-c60a-4a06-9c02-d4dcd74ef692',
        externalId: undefined,
        name: 'SKU',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Slug (url_slug)
       */
      url: {
        codename: 'url',
        id: '93ac7a11-2b9f-410c-9ce7-9d95e90b0960',
        externalId: undefined,
        name: 'Slug',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '11b1fdeb-c495-4b26-9004-7eb7d1cc1fef',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       *
       * Write a unique title tag for each pageBe brief, but descriptiveAvoid generic and vague titlesUse sentence case or title caseCreate something click-worthy—not clickbaitMatch search intentInclude your target keyword where it makes senseKeep it under 60 characters
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: '7a871a0b-4ef9-4eac-a2f1-274605253faa',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },
    },
  },

  /**
   * Product Listing
   */
  product_listing: {
    codename: 'product_listing',
    id: '18b3b0be-6bd3-47a8-8edb-7d4708089ce2',
    externalId: undefined,
    name: 'Product Listing',
    elements: {
      /**
       * Product category (taxonomy)
       */
      product_category: {
        codename: 'product_category',
        id: '675d419a-5bab-4483-88c1-8fb9c09f991a',
        externalId: undefined,
        name: 'Product category',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '151600b5-f75c-456e-9e56-ac43cea763ad',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Robots.txt
   */
  robots_txt: {
    codename: 'robots_txt',
    id: '73c0aa87-131e-459c-bdcd-0d4942d16c85',
    externalId: undefined,
    name: 'Robots.txt',
    elements: {
      /**
       * Content (text)
       */
      content: {
        codename: 'content',
        id: 'ba26d3a5-9f88-422e-bcb5-4b9bc85a85e2',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Site Configuration
   */
  site_configuration: {
    codename: 'site_configuration',
    id: '971ded8c-469f-476d-b7c4-716842db4027',
    externalId: undefined,
    name: 'Site Configuration',
    elements: {
      /**
       * Create new trial (custom)
       */
      create_new_trial: {
        codename: 'create_new_trial',
        id: '98740228-7d68-47a2-8b2a-854696fbac6c',
        externalId: undefined,
        name: 'Create new trial',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },

      /**
       * Search Corporate (custom)
       */
      search_corporate: {
        codename: 'search_corporate',
        id: 'deff17fe-9434-481d-ad00-6aef09a62b9b',
        externalId: undefined,
        name: 'Search Corporate',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },

      /**
       * Translation (custom)
       */
      translation: {
        codename: 'translation',
        id: '1fd5cae8-cd8a-46fd-80f4-18c92897d543',
        externalId: undefined,
        name: 'Translation',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Testimonial
   */
  testimonial: {
    codename: 'testimonial',
    id: 'd30689be-9900-4d54-a549-e919346f7990',
    externalId: undefined,
    name: 'Testimonial',
    elements: {
      /**
       * Author (modular_content)
       */
      author: {
        codename: 'author',
        id: 'f60caa40-5a31-47e8-9e3c-be862631381c',
        externalId: undefined,
        name: 'Author',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Quote (text)
       */
      quote: {
        codename: 'quote',
        id: 'b0a76be2-49f9-44d0-a565-bf61f70f0c93',
        externalId: undefined,
        name: 'Quote',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * YouTube Embed
   */
  youtube_embed: {
    codename: 'youtube_embed',
    id: '269c7ce3-1d74-41cd-bd35-2d5530aab4b3',
    externalId: undefined,
    name: 'YouTube Embed',
    elements: {
      /**
       * Autoplay (multiple_choice)
       */
      autoplay: {
        codename: 'autoplay',
        id: 'd59de605-0b0a-4e6f-9758-236a8cda250f',
        externalId: undefined,
        name: 'Autoplay',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Body (rich_text)
       */
      body: {
        codename: 'body',
        id: 'a2b286f6-be90-4ba4-83b7-fd217b1cecfb',
        externalId: undefined,
        name: 'Body',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * End time (number)
       *
       * Time in seconds, so if you want to end the video at 1:30 you fill in 90
       */
      end_time: {
        codename: 'end_time',
        id: '7b78f5bf-8fe1-4fb2-ac57-32f9058862c7',
        externalId: undefined,
        name: 'End time',
        required: false,
        type: 'number',
        snippetCodename: undefined,
      },

      /**
       * Image (asset)
       */
      image: {
        codename: 'image',
        id: '22365200-26af-4dd7-a41b-23f2807dca56',
        externalId: undefined,
        name: 'Image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Start time (number)
       *
       * Time in seconds, so if you want to end the video at 1:30 you fill in 90
       */
      start_time: {
        codename: 'start_time',
        id: '54a9d1b9-98bb-4e62-8b7c-f3a55d82f701',
        externalId: undefined,
        name: 'Start time',
        required: false,
        type: 'number',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'e5b3b337-e250-47a6-a5f7-7dfd8cccd6fd',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * YouTube (custom)
       */
      youtube: {
        codename: 'youtube',
        id: '216caf7c-b592-4517-ae81-54fa69fa2d1f',
        externalId: undefined,
        name: 'YouTube',
        required: true,
        type: 'custom',
        snippetCodename: undefined,
      },
    },
  },
} as const;
