/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const languages = {
    /**
     * Dutch   Netherlands
     */
    nlNL: {
        codename: 'nl-NL',
        id: '5e691b8f-50cd-4915-a91c-a2cc83a30855',
        isActive: false,
        isDefault: false,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined,
        name: 'Dutch - Netherlands'
    },

    /**
     * English   United Kingdom
     */
    enGB: {
        codename: 'en-GB',
        id: '00000000-0000-0000-0000-000000000000',
        isActive: true,
        isDefault: true,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined,
        name: 'English - United Kingdom'
    },

    /**
     * English   United States
     */
    enUS: {
        codename: 'en-US',
        id: '48c556ab-0c23-4888-b219-56ac3d9b3426',
        isActive: true,
        isDefault: false,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined,
        name: 'English - United States'
    },

    /**
     * French   French
     */
    frFR: {
        codename: 'fr-FR',
        id: '1fe00a59-5263-4e73-ab80-c70f28a72bd1',
        isActive: true,
        isDefault: false,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined,
        name: 'French - French'
    },

    /**
     * Spanish   Spain
     */
    esES: {
        codename: 'es-ES',
        id: '8e82d54e-65dc-4684-b5ac-ce7ad07ac519',
        isActive: true,
        isDefault: false,
        fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
        externalId: undefined,
        name: 'Spanish - Spain'
    }
} as const;
