/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: 🪙 Compare the Market
 * Environment: Production
 * Project Id: de84585d-59fc-0190-f8dd-12e74a4d633f
 */
export const languages = {
  /**
   * Eng - Gaelic (Scotland)
   */
  enGD: {
    codename: 'en-GD',
    id: '5e691b8f-50cd-4915-a91c-a2cc83a30855',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Eng - Gaelic (Scotland)',
  },

  /**
   * English - Australia
   */
  enAU: {
    codename: 'en-AU',
    id: '48c556ab-0c23-4888-b219-56ac3d9b3426',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'English - Australia',
  },

  /**
   * English - United Kingdom
   */
  enGB: {
    codename: 'en-GB',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'English - United Kingdom',
  },

  /**
   * French - French
   */
  frFR: {
    codename: 'fr-FR',
    id: '1fe00a59-5263-4e73-ab80-c70f28a72bd1',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'French - French',
  },

  /**
   * Spanish - Spain
   */
  esES: {
    codename: 'es-ES',
    id: '8e82d54e-65dc-4684-b5ac-ce7ad07ac519',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Spanish - Spain',
  },
} as const;
