/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: 🪙 Compare the Market
 * Environment: Production
 * Project Id: de84585d-59fc-0190-f8dd-12e74a4d633f
 */
export const roles = {} as const;
