/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: ⚒ EliteBuild Manufacturing - Master
 * Environment: Production
 * Project Id: 70a09beb-cba0-01b9-425e-a7af1bd1112f
 */
export const roles = {} as const;
