/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const taxonomies = {
    /**
     * Article Category
     */
    article_type: {
        codename: 'article_type',
        id: '056cd0d4-6b76-4d5a-b8d9-b36a87ade13f',
        externalId: undefined,
        name: 'Article Category',
        terms: {
            company: {
                codename: 'company',
                id: '18f93025-c8fc-4ca0-bd8a-f1017db9c60c',
                externalId: undefined,
                name: 'Company',
                terms: {
                    client_support_and_satisfaction: {
                        codename: 'client_support_and_satisfaction',
                        id: 'e8ddc487-6065-4c5c-af3b-8940564894d0',
                        externalId: undefined,
                        name: 'Client Support and Satisfaction',
                        terms: {}
                    },
                    history: {
                        codename: 'history',
                        id: 'ed6e038f-0081-4ea9-8c19-1b9da74b3242',
                        externalId: undefined,
                        name: 'History',
                        terms: {}
                    },
                    investors: {
                        codename: 'investors',
                        id: '02c9f23f-83bb-4b39-ad8c-cee7ea014bac',
                        externalId: undefined,
                        name: 'Investors',
                        terms: {}
                    },
                    research_and_development_: {
                        codename: 'research_and_development_',
                        id: 'f1d466ba-bb59-41aa-8303-f4db04aa019e',
                        externalId: undefined,
                        name: 'Research and Development ',
                        terms: {}
                    }
                }
            },
            product_spotlights: {
                codename: 'product_spotlights',
                id: '53b5a15e-4461-4df1-8b61-ccec9a0fb84c',
                externalId: undefined,
                name: 'News',
                terms: {
                    energy: {
                        codename: 'energy',
                        id: 'bc34bfe1-3c6a-409b-ae4c-6c6abd519dd7',
                        externalId: undefined,
                        name: 'Energy',
                        terms: {}
                    },
                    flux_capacitor: {
                        codename: 'flux_capacitor',
                        id: 'c5e2306c-8436-40d0-a6ea-e7ee01e03bdc',
                        externalId: undefined,
                        name: 'Flux Capacitor',
                        terms: {}
                    },
                    learning_and_adaptation: {
                        codename: 'learning_and_adaptation',
                        id: '3116b1c0-dcad-4fab-a60e-dc6fd9fb02e5',
                        externalId: undefined,
                        name: 'Learning and Adaptation',
                        terms: {}
                    },
                    plutonium: {
                        codename: 'plutonium',
                        id: 'bfcc64bd-f990-4cc4-9867-1243b0887673',
                        externalId: undefined,
                        name: 'Plutonium',
                        terms: {}
                    },
                    recyclables: {
                        codename: 'recyclables',
                        id: '3ae46b48-22d2-4a1a-8b73-852dae5723f6',
                        externalId: undefined,
                        name: 'Recyclables',
                        terms: {}
                    },
                    renewable_energy: {
                        codename: 'renewable_energy',
                        id: '7849ba24-786d-4aaf-98c9-936bfba8a18e',
                        externalId: undefined,
                        name: 'Renewable Energy',
                        terms: {}
                    },
                    sustainability_: {
                        codename: 'sustainability_',
                        id: '72f4cb84-62f5-4125-9765-5c8aafc7ece3',
                        externalId: undefined,
                        name: 'Sustainability ',
                        terms: {}
                    },
                    waste: {
                        codename: 'waste',
                        id: 'c0b86706-4464-420c-8983-4221fd037c47',
                        externalId: undefined,
                        name: 'Waste',
                        terms: {}
                    }
                }
            },
            sustainability_and_green_manufacturing: {
                codename: 'sustainability_and_green_manufacturing',
                id: '2b76f52e-3c51-4ae3-bb43-000b78aa470f',
                externalId: undefined,
                name: 'Partners',
                terms: {
                    customer_success_stories: {
                        codename: 'customer_success_stories',
                        id: '38225c12-27b1-41dc-91de-a2d7c0fe7f0d',
                        externalId: undefined,
                        name: 'Customer Success Stories',
                        terms: {}
                    }
                }
            },
            industry_trends_and_insights: {
                codename: 'industry_trends_and_insights',
                id: 'e14c44d2-c89d-4fab-8a8f-376dc2b63a5d',
                externalId: undefined,
                name: 'Products',
                terms: {
                    ai: {
                        codename: 'ai',
                        id: '97101168-eeac-4596-aa1d-1fdc9ddf4be2',
                        externalId: undefined,
                        name: 'AI',
                        terms: {}
                    },
                    engineering_: {
                        codename: 'engineering_',
                        id: '6f713926-9058-49d9-bcdd-6983291352e6',
                        externalId: undefined,
                        name: 'Engineering ',
                        terms: {}
                    },
                    industry_revolution: {
                        codename: 'industry_revolution',
                        id: 'af9b3c19-587f-41cc-b2ab-750f056c305d',
                        externalId: undefined,
                        name: 'Industry Revolution',
                        terms: {}
                    },
                    innovation_: {
                        codename: 'innovation_',
                        id: 'e310ccef-dfe3-42c5-b4a6-b47cb849f787',
                        externalId: undefined,
                        name: 'Innovation ',
                        terms: {}
                    },
                    robotics_: {
                        codename: 'robotics_',
                        id: '5ba9a91a-316e-47a8-ab78-b4769c52e67e',
                        externalId: undefined,
                        name: 'Robotics ',
                        terms: {}
                    },
                    technology_: {
                        codename: 'technology_',
                        id: 'f9b49a80-c653-4553-a076-714b0b25d390',
                        externalId: undefined,
                        name: 'Technology ',
                        terms: {}
                    },
                    time_travel: {
                        codename: 'time_travel',
                        id: '69900f08-a59c-49a6-ba05-0ae6ccd04876',
                        externalId: undefined,
                        name: 'Time Travel',
                        terms: {}
                    }
                }
            }
        }
    },

    /**
     * Channels
     */
    channels: {
        codename: 'channels',
        id: '06a7a661-2c35-483a-bf0a-a296717ea888',
        externalId: undefined,
        name: 'Channels',
        terms: {
            desktop: {
                codename: 'desktop',
                id: '35250ae7-3a2c-431a-abf5-3cb29ca725fc',
                externalId: undefined,
                name: 'Desktop',
                terms: {}
            },
            display: {
                codename: 'display',
                id: 'f1933425-bdf1-4e0f-8f14-909a33fe2712',
                externalId: undefined,
                name: 'Display',
                terms: {}
            },
            mobile: {
                codename: 'mobile',
                id: '49a8bf44-54b8-4d73-83de-ec276ba72272',
                externalId: undefined,
                name: 'Mobile',
                terms: {}
            },
            social: {
                codename: 'social',
                id: '8031adbf-b415-4940-b040-fcb7b4b9f895',
                externalId: undefined,
                name: 'Social',
                terms: {
                    facebook: {
                        codename: 'facebook',
                        id: 'c29a4db6-f909-4973-aa0b-5f68eb3bb669',
                        externalId: undefined,
                        name: 'Facebook',
                        terms: {}
                    },
                    instagram: {
                        codename: 'instagram',
                        id: '27a70ea2-1999-480b-9bab-619e628a6f6b',
                        externalId: undefined,
                        name: 'Instagram',
                        terms: {}
                    },
                    x: {
                        codename: 'x',
                        id: '462c4f72-faca-4b94-866e-f7fca17af4c5',
                        externalId: undefined,
                        name: 'X',
                        terms: {}
                    }
                }
            },
            tablet: {
                codename: 'tablet',
                id: 'e7eac922-afc1-4c54-8ce1-0ddce451246f',
                externalId: undefined,
                name: 'Tablet',
                terms: {}
            }
        }
    },

    /**
     * Course category
     */
    course_category: {
        codename: 'course_category',
        id: '4c0bd375-e44e-4b92-bfbd-e9e5029352af',
        externalId: undefined,
        name: 'Course category',
        terms: {
            allied_health_professions_and_public_health: {
                codename: 'allied_health_professions_and_public_health',
                id: '478b3c79-2b8a-4c7b-a963-25b913e892bd',
                externalId: undefined,
                name: 'Allied Health Professions and Public Health',
                terms: {}
            },
            art_and_design: {
                codename: 'art_and_design',
                id: '1acc7c2b-dfc5-4c44-816b-73d02940412d',
                externalId: undefined,
                name: 'Art and Design',
                terms: {}
            },
            business_and_management: {
                codename: 'business_and_management',
                id: '7b8bdb07-c519-4860-8fa6-695a213a3124',
                externalId: undefined,
                name: 'Business and Management',
                terms: {}
            },
            computer_science: {
                codename: 'computer_science',
                id: '4c142815-447d-4663-944d-da8cbb8ef4fb',
                externalId: undefined,
                name: 'Computer Science',
                terms: {}
            },
            crime__policing_and_investigation: {
                codename: 'crime__policing_and_investigation',
                id: '22d841a3-c0c2-454a-84e8-34167169ee91',
                externalId: undefined,
                name: 'Crime, Policing and Investigation',
                terms: {}
            },
            engineering: {
                codename: 'engineering',
                id: '6c562a8c-1e61-4ac8-af5b-2a0feb4d4d99',
                externalId: undefined,
                name: 'Engineering',
                terms: {}
            },
            health_and_clinical_sciences: {
                codename: 'health_and_clinical_sciences',
                id: '4dd44625-07e6-444c-959e-ba23024d29f3',
                externalId: undefined,
                name: 'Health and Clinical Sciences',
                terms: {}
            }
        }
    },

    /**
     * Course type
     */
    course_type: {
        codename: 'course_type',
        id: '0531e34e-3fdd-423e-9d6c-1d25abfd8a48',
        externalId: undefined,
        name: 'Course type',
        terms: {
            ba__hons_: {
                codename: 'ba__hons_',
                id: 'ea6d8efb-bde8-4e98-b1ee-d48172243b49',
                externalId: undefined,
                name: 'BA (Hons)',
                terms: {}
            },
            bsc__hons__: {
                codename: 'bsc__hons__',
                id: 'a142b453-af81-4c56-a9e8-ee95b6dc19fc',
                externalId: undefined,
                name: 'BSc (Hons) ',
                terms: {}
            },
            mba: {
                codename: 'mba',
                id: 'a7784736-aa8a-4bdb-9efe-283fe4beca27',
                externalId: undefined,
                name: 'MBA',
                terms: {}
            }
        }
    },

    /**
     * Enrollment Status
     */
    enrollment_status: {
        codename: 'enrollment_status',
        id: 'f58f9974-0717-4214-9696-df815d799ac3',
        externalId: undefined,
        name: 'Enrollment Status',
        terms: {
            full_time: {
                codename: 'full_time',
                id: '0f951841-6548-440e-9217-3d9df67411c8',
                externalId: undefined,
                name: 'Full-time',
                terms: {}
            },
            part_time: {
                codename: 'part_time',
                id: '3c89efaf-639c-465d-aacc-d82f720df18e',
                externalId: undefined,
                name: 'Part-time',
                terms: {}
            }
        }
    },

    /**
     * Event Type
     */
    event_type: {
        codename: 'event_type',
        id: '1d733339-ad82-4e7b-8ce3-969528c7ac5e',
        externalId: undefined,
        name: 'Event Type',
        terms: {
            jumps_racing: {
                codename: 'jumps_racing',
                id: '65d0888d-9119-46dd-9704-3e11ac527063',
                externalId: undefined,
                name: 'Announcements',
                terms: {}
            },
            royal_ascot: {
                codename: 'royal_ascot',
                id: 'd1bd1a18-cac3-4e86-b284-bd1972be324c',
                externalId: undefined,
                name: 'Q&A',
                terms: {}
            },
            flat_racing: {
                codename: 'flat_racing',
                id: '9063575b-cdd8-4bac-ba34-d4b7b2312ddd',
                externalId: undefined,
                name: 'Training',
                terms: {}
            },
            family_days: {
                codename: 'family_days',
                id: 'd12b0964-f2b1-4423-b309-0dd6ab14e0b3',
                externalId: undefined,
                name: 'Webinar',
                terms: {}
            }
        }
    },

    /**
     * Navigation Structures
     */
    navigation_structures: {
        codename: 'navigation_structures',
        id: '151341b3-1e49-4793-8649-d56419382f2f',
        externalId: undefined,
        name: 'Navigation Structures',
        terms: {
            footer: {
                codename: 'footer',
                id: 'bbc069b1-9c9a-4090-933b-e6636bf2a7b7',
                externalId: undefined,
                name: 'Footer',
                terms: {}
            },
            header: {
                codename: 'header',
                id: '2b71d1a8-4789-4ff7-b3ec-c7172f5880c0',
                externalId: undefined,
                name: 'Header',
                terms: {}
            }
        }
    },

    /**
     * Product category
     */
    product_category: {
        codename: 'product_category',
        id: 'a924d361-0fdb-4fe1-97e6-6de20e73381a',
        externalId: undefined,
        name: 'Product category',
        terms: {
            circuitboards_and_electronics: {
                codename: 'circuitboards_and_electronics',
                id: '0fb68394-caf7-4702-ac45-4432768da4dd',
                externalId: undefined,
                name: 'Circuitboards and Electronics',
                terms: {}
            },
            electronic_cabling_: {
                codename: 'electronic_cabling_',
                id: 'dcd24575-f9f6-458b-8550-70eeeac98f66',
                externalId: undefined,
                name: 'Electronic Cabling ',
                terms: {}
            },
            robotics: {
                codename: 'robotics',
                id: '60304833-151c-41f6-9433-86c58f376306',
                externalId: undefined,
                name: 'Robotics and AI',
                terms: {}
            },
            smart_home_appliances: {
                codename: 'smart_home_appliances',
                id: '299a7ba6-460c-433f-b2c5-a4428650f548',
                externalId: undefined,
                name: 'Smart Home Appliances',
                terms: {}
            },
            time_travel_components: {
                codename: 'time_travel_components',
                id: 'ca7d7c0b-786f-412c-8c44-3a2f92badc56',
                externalId: undefined,
                name: 'Time Travel Components',
                terms: {}
            }
        }
    }
} as const;
