/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: 🪙 Compare the Market
 * Environment: Production
 * Project Id: de84585d-59fc-0190-f8dd-12e74a4d633f
 */
export const taxonomies = {
  /**
   * Article Category
   */
  article_type: {
    codename: 'article_type',
    id: '056cd0d4-6b76-4d5a-b8d9-b36a87ade13f',
    externalId: undefined,
    name: 'Article Category',
    terms: {
      product_spotlights: {
        codename: 'product_spotlights',
        id: '53b5a15e-4461-4df1-8b61-ccec9a0fb84c',
        externalId: undefined,
        name: 'News',
        terms: {},
      },
      sustainability_and_green_manufacturing: {
        codename: 'sustainability_and_green_manufacturing',
        id: '2b76f52e-3c51-4ae3-bb43-000b78aa470f',
        externalId: undefined,
        name: 'Partners',
        terms: {},
      },
      industry_trends_and_insights: {
        codename: 'industry_trends_and_insights',
        id: 'e14c44d2-c89d-4fab-8a8f-376dc2b63a5d',
        externalId: undefined,
        name: 'Products',
        terms: {},
      },
    },
  },

  /**
   * Channels
   */
  channels: {
    codename: 'channels',
    id: '06a7a661-2c35-483a-bf0a-a296717ea888',
    externalId: undefined,
    name: 'Channels',
    terms: {
      display: {
        codename: 'display',
        id: '5b6e63c9-c849-4957-9c73-aca5922c1939',
        externalId: undefined,
        name: 'Display',
        terms: {},
      },
      karma_website: {
        codename: 'karma_website',
        id: '59029511-0d88-4062-86fb-2ab421f534c3',
        externalId: undefined,
        name: 'Karma Website',
        terms: {},
      },
    },
  },

  /**
   * Course category
   */
  course_category: {
    codename: 'course_category',
    id: '4c0bd375-e44e-4b92-bfbd-e9e5029352af',
    externalId: undefined,
    name: 'Course category',
    terms: {
      allied_health_professions_and_public_health: {
        codename: 'allied_health_professions_and_public_health',
        id: '478b3c79-2b8a-4c7b-a963-25b913e892bd',
        externalId: undefined,
        name: 'Allied Health Professions and Public Health',
        terms: {},
      },
      art_and_design: {
        codename: 'art_and_design',
        id: '1acc7c2b-dfc5-4c44-816b-73d02940412d',
        externalId: undefined,
        name: 'Art and Design',
        terms: {},
      },
      business_and_management: {
        codename: 'business_and_management',
        id: '7b8bdb07-c519-4860-8fa6-695a213a3124',
        externalId: undefined,
        name: 'Business and Management',
        terms: {},
      },
      computer_science: {
        codename: 'computer_science',
        id: '4c142815-447d-4663-944d-da8cbb8ef4fb',
        externalId: undefined,
        name: 'Computer Science',
        terms: {},
      },
      crime__policing_and_investigation: {
        codename: 'crime__policing_and_investigation',
        id: '22d841a3-c0c2-454a-84e8-34167169ee91',
        externalId: undefined,
        name: 'Crime, Policing and Investigation',
        terms: {},
      },
      engineering: {
        codename: 'engineering',
        id: '6c562a8c-1e61-4ac8-af5b-2a0feb4d4d99',
        externalId: undefined,
        name: 'Engineering',
        terms: {},
      },
      health_and_clinical_sciences: {
        codename: 'health_and_clinical_sciences',
        id: '4dd44625-07e6-444c-959e-ba23024d29f3',
        externalId: undefined,
        name: 'Health and Clinical Sciences',
        terms: {},
      },
    },
  },

  /**
   * Course type
   */
  course_type: {
    codename: 'course_type',
    id: '0531e34e-3fdd-423e-9d6c-1d25abfd8a48',
    externalId: undefined,
    name: 'Course type',
    terms: {
      ba__hons_: {
        codename: 'ba__hons_',
        id: 'ea6d8efb-bde8-4e98-b1ee-d48172243b49',
        externalId: undefined,
        name: 'BA (Hons)',
        terms: {},
      },
      bsc__hons__: {
        codename: 'bsc__hons__',
        id: 'a142b453-af81-4c56-a9e8-ee95b6dc19fc',
        externalId: undefined,
        name: 'BSc (Hons) ',
        terms: {},
      },
      mba: {
        codename: 'mba',
        id: 'a7784736-aa8a-4bdb-9efe-283fe4beca27',
        externalId: undefined,
        name: 'MBA',
        terms: {},
      },
    },
  },

  /**
   * Enrollment Status
   */
  enrollment_status: {
    codename: 'enrollment_status',
    id: 'f58f9974-0717-4214-9696-df815d799ac3',
    externalId: undefined,
    name: 'Enrollment Status',
    terms: {
      full_time: {
        codename: 'full_time',
        id: '0f951841-6548-440e-9217-3d9df67411c8',
        externalId: undefined,
        name: 'Full-time',
        terms: {},
      },
      part_time: {
        codename: 'part_time',
        id: '3c89efaf-639c-465d-aacc-d82f720df18e',
        externalId: undefined,
        name: 'Part-time',
        terms: {},
      },
    },
  },

  /**
   * Event Type
   */
  event_type: {
    codename: 'event_type',
    id: '1d733339-ad82-4e7b-8ce3-969528c7ac5e',
    externalId: undefined,
    name: 'Event Type',
    terms: {
      jumps_racing: {
        codename: 'jumps_racing',
        id: '65d0888d-9119-46dd-9704-3e11ac527063',
        externalId: undefined,
        name: 'Announcements',
        terms: {},
      },
      royal_ascot: {
        codename: 'royal_ascot',
        id: 'd1bd1a18-cac3-4e86-b284-bd1972be324c',
        externalId: undefined,
        name: 'Q&A',
        terms: {},
      },
      flat_racing: {
        codename: 'flat_racing',
        id: '9063575b-cdd8-4bac-ba34-d4b7b2312ddd',
        externalId: undefined,
        name: 'Training',
        terms: {},
      },
      family_days: {
        codename: 'family_days',
        id: 'd12b0964-f2b1-4423-b309-0dd6ab14e0b3',
        externalId: undefined,
        name: 'Webinar',
        terms: {},
      },
    },
  },

  /**
   * Navigation Structures
   */
  navigation_structures: {
    codename: 'navigation_structures',
    id: '151341b3-1e49-4793-8649-d56419382f2f',
    externalId: undefined,
    name: 'Navigation Structures',
    terms: {
      footer: {
        codename: 'footer',
        id: 'bbc069b1-9c9a-4090-933b-e6636bf2a7b7',
        externalId: undefined,
        name: 'Footer',
        terms: {},
      },
      header: {
        codename: 'header',
        id: '2b71d1a8-4789-4ff7-b3ec-c7172f5880c0',
        externalId: undefined,
        name: 'Header',
        terms: {},
      },
    },
  },

  /**
   * Personas
   */
  personas: {
    codename: 'personas',
    id: '79481e3e-273d-42f8-b4b7-cd2c865fc067',
    externalId: undefined,
    name: 'Personas',
    terms: {
      the_budget_minded_consumer: {
        codename: 'the_budget_minded_consumer',
        id: '32ce3222-de15-4e07-b43c-d0653e4867ba',
        externalId: undefined,
        name: 'The Budget-Minded Consumer',
        terms: {},
      },
      the_environmentally_conscious_consumer: {
        codename: 'the_environmentally_conscious_consumer',
        id: '494c6aba-6f13-4059-8f8a-9136779b3909',
        externalId: undefined,
        name: 'The Environmentally Conscious Consumer',
        terms: {},
      },
      the_family_oriented_parent: {
        codename: 'the_family_oriented_parent',
        id: 'a7167fe4-aa80-4e61-9085-74620b8d8610',
        externalId: undefined,
        name: 'The Family-Oriented Parent',
        terms: {},
      },
      the_tech_savvy_millennial: {
        codename: 'the_tech_savvy_millennial',
        id: '7d6ca4d3-1e9b-4e81-a78a-a72fba9558cd',
        externalId: undefined,
        name: 'The Tech-Savvy Millennial',
        terms: {},
      },
    },
  },

  /**
   * Product category
   */
  product_category: {
    codename: 'product_category',
    id: 'a924d361-0fdb-4fe1-97e6-6de20e73381a',
    externalId: undefined,
    name: 'Product category',
    terms: {
      circuitboards_and_electronics: {
        codename: 'circuitboards_and_electronics',
        id: '0fb68394-caf7-4702-ac45-4432768da4dd',
        externalId: undefined,
        name: 'Circuitboards and Electronics',
        terms: {},
      },
      electronic_cabling_: {
        codename: 'electronic_cabling_',
        id: 'dcd24575-f9f6-458b-8550-70eeeac98f66',
        externalId: undefined,
        name: 'Electronic Cabling ',
        terms: {},
      },
      robotics: {
        codename: 'robotics',
        id: '60304833-151c-41f6-9433-86c58f376306',
        externalId: undefined,
        name: 'Robotics and AI',
        terms: {},
      },
      smart_home_appliances: {
        codename: 'smart_home_appliances',
        id: '299a7ba6-460c-433f-b2c5-a4428650f548',
        externalId: undefined,
        name: 'Smart Home Appliances',
        terms: {},
      },
      time_travel_components: {
        codename: 'time_travel_components',
        id: 'ca7d7c0b-786f-412c-8c44-3a2f92badc56',
        externalId: undefined,
        name: 'Time Travel Components',
        terms: {},
      },
    },
  },

  /**
   * Products
   */
  products: {
    codename: 'products',
    id: '65ed694b-948a-4b5f-8c38-f1847c30fb39',
    externalId: undefined,
    name: 'Products',
    terms: {
      all: {
        codename: 'all',
        id: '69300d6f-ce4d-4385-8501-1e75d680a003',
        externalId: undefined,
        name: 'All',
        terms: {},
      },
      car: {
        codename: 'car',
        id: '2addd539-e98d-445a-8e92-c316a0c30bae',
        externalId: undefined,
        name: 'Car',
        terms: {},
      },
      home: {
        codename: 'home',
        id: 'f479d864-24ac-4944-91ff-a6ee63d030d5',
        externalId: undefined,
        name: 'Home',
        terms: {},
      },
      travel: {
        codename: 'travel',
        id: '5cc245c0-d92a-48da-995e-2792dc0a851f',
        externalId: undefined,
        name: 'Travel',
        terms: {},
      },
    },
  },
} as const;
