/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: ⚒ EliteBuild Manufacturing
 * Environment: Production
 * Project Id: 768414e0-b626-0188-3a49-5d5d02e33dda
 */
export const taxonomies = {
  /**
   * Article Category
   */
  article_type: {
    codename: 'article_type',
    id: '056cd0d4-6b76-4d5a-b8d9-b36a87ade13f',
    externalId: undefined,
    name: 'Article Category',
    terms: {
      company_news_and_updates: {
        codename: 'company_news_and_updates',
        id: '33548ecc-5df2-4361-b23c-ecd7f83fa2db',
        externalId: undefined,
        name: 'About us',
        terms: {},
      },
      sustainability_and_green_manufacturing: {
        codename: 'sustainability_and_green_manufacturing',
        id: '2b76f52e-3c51-4ae3-bb43-000b78aa470f',
        externalId: undefined,
        name: 'Investors',
        terms: {},
      },
      product_spotlights: {
        codename: 'product_spotlights',
        id: '53b5a15e-4461-4df1-8b61-ccec9a0fb84c',
        externalId: undefined,
        name: 'News',
        terms: {},
      },
      industry_trends_and_insights: {
        codename: 'industry_trends_and_insights',
        id: 'e14c44d2-c89d-4fab-8a8f-376dc2b63a5d',
        externalId: undefined,
        name: 'Products',
        terms: {},
      },
    },
  },

  /**
   * Event Type
   */
  event_type: {
    codename: 'event_type',
    id: '1d733339-ad82-4e7b-8ce3-969528c7ac5e',
    externalId: undefined,
    name: 'Event Type',
    terms: {
      family_days: {
        codename: 'family_days',
        id: 'd12b0964-f2b1-4423-b309-0dd6ab14e0b3',
        externalId: undefined,
        name: 'Curriculum Connect',
        terms: {},
      },
      flat_racing: {
        codename: 'flat_racing',
        id: '9063575b-cdd8-4bac-ba34-d4b7b2312ddd',
        externalId: undefined,
        name: 'Feedback',
        terms: {},
      },
      royal_ascot: {
        codename: 'royal_ascot',
        id: 'd1bd1a18-cac3-4e86-b284-bd1972be324c',
        externalId: undefined,
        name: 'Senior Leadership',
        terms: {},
      },
      jumps_racing: {
        codename: 'jumps_racing',
        id: '65d0888d-9119-46dd-9704-3e11ac527063',
        externalId: undefined,
        name: 'Teacher standardisation',
        terms: {},
      },
    },
  },

  /**
   * Product category
   */
  product_category: {
    codename: 'product_category',
    id: 'a924d361-0fdb-4fe1-97e6-6de20e73381a',
    externalId: undefined,
    name: 'Product category',
    terms: {
      appliances: {
        codename: 'appliances',
        id: 'aeb781d9-4650-4a14-a606-d443d23de808',
        externalId: undefined,
        name: 'Bracelets',
        terms: {},
      },
      outdoor_equipment: {
        codename: 'outdoor_equipment',
        id: '32d99b92-19f6-45ea-883c-25e0699dbf4c',
        externalId: undefined,
        name: 'Earrings',
        terms: {},
      },
      commercial_equipment: {
        codename: 'commercial_equipment',
        id: '56037861-921d-41ff-b83c-b276fd52a00d',
        externalId: undefined,
        name: 'Necklace',
        terms: {},
      },
      smart_home_solutions: {
        codename: 'smart_home_solutions',
        id: '1aea0f2c-66d4-4bfb-a279-6bdef5edc32a',
        externalId: undefined,
        name: 'Rings',
        terms: {},
      },
    },
  },
} as const;
