/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: ⚒ EliteBuild Manufacturing
 * Environment: Production
 * Project Id: 768414e0-b626-0188-3a49-5d5d02e33dda
 */
export const webhooks = {
  /**
   * Automatic Translation
   */
  automaticTranslation: {
    url: 'https://elitebuild.kontent.dev/api/translate-webhook/',
    id: '352d76ae-9060-4bf6-84cd-d5ca66538525',
    name: 'Automatic Translation',
  },
} as const;
