/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: ⚒ Karma Manufacturing
 * Environment: Production
 * Project Id: a917b5bf-e2e1-011e-0a73-0b317b1e1c33
 */
export const workflows = {
  /**
   * Component Workflow
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  component_workflow: {
    codename: 'component_workflow',
    id: 'a5ec0fb2-e582-40fc-855c-f261337d82ac',
    name: 'Component Workflow',
  },

  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
} as const;
